/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

exports.MetadataIndex = require('./metadataIndex');
exports.Metadata = require('./metadata');
exports.InstitutionData = require('./institutionData');
exports.Institution = require('./institution');
exports.Pathsinstitutionsgetresponses200contentapplicationJsonschema = require('./pathsinstitutionsgetresponses200contentapplicationJsonschema');
exports.LocationData = require('./locationData');
exports.Location = require('./location');
exports.Pathslocationsgetresponses200contentapplicationJsonschema = require('./pathslocationsgetresponses200contentapplicationJsonschema');
exports.SummaryData = require('./summaryData');
exports.Summary = require('./summary');
exports.Pathssummarygetresponses200contentapplicationJsonschema = require('./pathssummarygetresponses200contentapplicationJsonschema');
exports.FailureData = require('./failureData');
exports.Failure = require('./failure');
exports.Totals = require('./totals');
exports.Pathsfailuresgetresponses200contentapplicationJsonschema = require('./pathsfailuresgetresponses200contentapplicationJsonschema');
