/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a InstitutionData.
 */
class InstitutionData {
  /**
   * Create a InstitutionData.
   * @property {string} [aCTIVE] Institutions that are currently open and
   * insured by the FDIC
   * @property {string} [aDDRESS] Street address at which the institution or
   * one of its branches is physically located.
   * @property {number} [aSSET] Total assets. The sum of all assets owned by
   * the institution including cash, loans, securities, bank premises and other
   * assets. This total does not include off-balance-sheet accounts.
   * @property {string} [bKCLASS] A classification code assigned by the FDIC
   * based on the institution's charter type (commercial bank or savings
   * institution), charter agent (state or federal), Federal Reserve membership
   * status (Fed member, Fed nonmember)and its primary federal regulator (state
   * chartered institutions are subject to both federal and state supervision).
   * N = commercial bank, national (federal) charter and Fed member, supervised
   * by the Office of the Comptroller of the Currency (OCC)  SM = commercial
   * bank, state charter and Fed member, supervised by the Federal Reserve
   * (FRB)  NM = commercial bank, state charter and Fed nonmember, supervised
   * by the FDIC  SB = savings banks, state charter, supervised by the FDIC  SA
   * = savings associations, state or federal charter, supervised by the Office
   * of Thrift Supervision (OTS)  OI = insured U.S. branch of a foreign
   * chartered institution (IBA). Possible values include: 'N', 'SM', 'NM',
   * 'SB', 'SA', 'OI'
   * @property {string} [cb] FDIC community banks are identified based on
   * criteria defined in the FDIC Community Banking Study. Using detailed
   * balance sheet and geographic data, the study defines communtiy banks in
   * terms of their traditional relationship banking and limited geographic
   * scope of operations
   * @property {string} [cBSA] The name associated with the numeric code that
   * the U.S. Census Bureau Office of Management and Budget assigns for the
   * CBSA. The 2000 standards provide that each CBSA must contain at least one
   * urban area of 10,000 or more population.  Metropolitan and micropolitan
   * statistical areas are two categories of core based statistical areas. If
   * an institution is not defined as a CBSA, the value of the field will be
   * zero. For more information see:
   * http://www.census.gov/population/www/estimates/metroarea.html .
   * @property {string} [cBSADIV] The name associated with the numeric code
   * given by the US Census Bureau office of Management and Budget (2000
   * standards) that represents the core based statistical division (CBSADIV).
   * A metropolitan division is a county or group of counties within a core
   * based statistical area that contains a core with a population of at least
   * 2.5 million. A CBSA metropolitan division consists of one or more
   * main/secondary counties that represent an employment center or centers,
   * plus adjacent counties associated with the main county or counties through
   * commuting ties. If an institution is not defined as a CBSA division the
   * value of the field will be zero.
   * @property {string} [cBSADIVFLG] A flag used to indicate whether an
   * institution is in a CBSA division 1=yes, 0=no
   * @property {string} [cBSADIVNO] The numeric code given by the US Census
   * Bureau office of Management and Budget that represents the core based
   * statistical division (CBSADIV)under the year 2000 standards. A
   * metropolitan division is a county or group of counties within a core based
   * statistical area that contains a core with a population of at least 2.5
   * million. A CBSA metropolitan division consists of one or more
   * main/secondary counties that represent an employment center or centers,
   * plus adjacent counties associated with the main county or counties through
   * commuting ties. If an institution is not defined as a CBSA division the
   * value of the field will be zero.
   * @property {string} [cBSAMETRO] Numeric code assigned by the U.S. Census
   * Bureau's Office of Management and Budget for a metropolitan area within a
   * CBSA
   * @property {string} [cBSAMETROFLG] A flag used to indicate whether an
   * institution is in a metropolitan statistical area.
   * @property {string} [cBSAMETRONAME] Name associated with the numeric code
   * that the U.S. Census Bureau's Office of Management and Budget assigns for
   * the metropolitan areas within a CBSA; are now also the basis for
   * Metropolitan Statistical Areas (MSAs)
   * @property {string} [cBSAMICROFLG] A flag used to indicate whether an
   * institution is in a micropolitan statistical area
   * @property {string} [cBSANO] The numeric code that the U.S. Census Bureaus
   * Office of Management and Budget assigns for the CBSA. The 2000 standards
   * provide that each CBSA must contain at least one urban area of 10,000 or
   * more population.  Metropolitan and micropolitan statistical areas are two
   * categories of core based statistical areas. If an institution is not
   * defined as a CBSA, the value of the field will be zero. For more
   * information see:
   * http://www.census.gov/population/www/estimates/metroarea.html .
   * @property {string} [cERT] A unique NUMBER assigned by the FDIC used to
   * identify institutions and for the issuance of insurance certificates.
   * @property {string} [cERTCONS] FDIC certificate number of the parent bank
   * or savings institution with which the reported institution’s financial
   * data has been consolidated. Beginning in March 1997, both the Thrift
   * Financial Reports and Call Reports are completed on a fully consolidated
   * basis.  Previously, the consolidation of subsidiary depository
   * institutions was prohibited.  Now, parent institutions are required to
   * file consolidated reports, while their subsidiary financial institutions
   * are still required to file separate reports.  Click on the certificate
   * number to identify the parent bank or thrift.
   * @property {date} [cFPBEFFDTE] Date the institution began secondary
   * supervision by CFPB
   * @property {date} [cFPBENDDTE] Date the institution ended supervision by
   * CFPB
   * @property {string} [cFPBFLAG] Indicates secondary supervision by CFPB ('0'
   * - not supervised by CFPB, '1'- secondarily supervised by CFPB)
   * @property {string} [cHANGEC1] FDIC code used to signify a structural event
   * relating to an institution.  Structure codes are as follows:
   * @property {string} [cHANGEC2] FDIC code used to signify a structural event
   * relating to an institution (see CHANGECODE for the key to the codes).
   * @property {string} [cHANGEC3] FDIC code used to signify a structural event
   * relating to an institution (see CHANGECODE for the key to the codes).
   * @property {string} [cHANGEC4] FDIC code used to signify a structural event
   * relating to an institution (see CHANGECODE for the key to the codes).
   * @property {string} [cHANGEC5] FDIC code used to signify a structural event
   * relating to an institution (see CHANGECODE for the key to the codes).
   * @property {string} [cHARTER] A unique number assigned by the Office of the
   * Comptroller of the Currency (OCC) used to identify institutions that it
   * has chartered and regulates (i.e. national  banks).
   * @property {string} [cHRTAGNT] All Chartering Agencies - State and Federal
   * Comptroller of the Currency - Chartering authority for nationally
   * chartered commercial banks and for federally chartered savings
   * associations (The Office of Thrift Supervision (OTS) before 7/21/11)
   * State (includes U.S. Territories) - Chartering authority for institutions
   * that are not chartered by the OCC or OTS
   * @property {string} [cITY] City in which an institution's headquarters or
   * one of its branches is physically located. Either the entire name or part
   * of the name of a specific city may be entered to produce an Institution
   * List.
   * @property {string} [cITYHCR] City in which the headquarters of the
   * institution's regulatory high holder are physically located.
   * @property {string} [cLCODE] Numeric code which identifies the major and
   * minor categories of an institution.
   * @property {string} [cMSANO] The numeric code given by the US Census Bureau
   * office of Management and Budget that represents the CMSA prior to the year
   * 2000 standards. 1=yes
   * @property {string} [cMSA] The Federal Information Processing Standards
   * (FIPS) Consolidated Metropolitan Statistical Area (CMSA) code is a number
   * representing the institution location. CMSA consists of two or more
   * contiguous Metropolitan Statistical Areas (MSA) with a combined population
   * of over 1 Million.  Note: If an institution is not located in a CMSA, the
   * value of the field will be zeroes.
   * @property {string} [cONSERVE] A flag (1=yes;0=no) that indicates if an
   * institution is being operated in government conservatorship.
   * @property {string} [cOUNTY] County where the institution is physically
   * located (abbreviated if the county name exceeds 16 characters).
   * @property {string} [cSA] The name associated with the numeric code that
   * the U.S. Census Bureau Office of Management and Budget assigns for the
   * combined statistical area (CSA) per the 2000 standards. If an institution
   * is not defined as a CSA, the value of the field will be blank. For more
   * information see:
   * http://www.census.gov/population/www/estimates/metroarea.html .
   * @property {string} [cSANO] The numeric code that the U.S. Census Bureau
   * Office of Management and Budget assigns for the combined statistical area
   * (CSA) per the 2000 standards. If an institution is not defined as a CSA,
   * the value of the field will be zero.  For more information see:
   * http://www.census.gov/population/www/estimates/metroarea.html .
   * @property {string} [cSAFLG] A flag used to indicate whether an institution
   * is in a Combined Statistical Area. 1=yes and 0=no.
   * @property {string} [dATEUPDT] The date of the last data update.
   * @property {string} [dENOVO] A flag used to indicate whether an institution
   * is a new institution (not a recharter). This flag is set quarterly. For
   * instance, if REPDTE is 3/31/98 and DENOVO equals 1, the institution was a
   * denovo during the first quarter of 1998.
   * @property {number} [dEP] Total deposits. The sum of all deposits including
   * demand deposits, money market deposits, other savings deposits, time
   * deposits and deposits in foreign offices.
   * @property {number} [dEPDOM] Deposits held in domestic offices. The sum of
   * all domestic office deposits, including demand deposits, money market
   * deposits, other savings deposits and time deposits.
   * @property {string} [dOCKET] An identification number assigned to
   * institutions chartered by the office of thrift supervision or members of
   * the federal housing finance board (FHFB) and formerly by the federal home
   * loan bank board.  The value is '00000' for institutions not members of the
   * FHFB.
   * @property {date} [eFFDATE] Effective Start Date of the data contained in
   * this row.
   * @property {string} [eNDEFYMD] The date that ends or closes out the last
   * structural event relating to an institution. For closed institutions, this
   * date represents the day that the institution became inactive.
   * @property {string} [eq] Total equity capital (includes preferred and
   * common stock, surplus and undivided profits).
   * @property {date} [eSTYMD] The date on which the institution began
   * operations.
   * @property {string} [fDICDBS] The FDIC Office assigned to the geographic
   * area.  The eight FDIC Regions and their respective states are:    Boston -
   * Connecticut, Maine, Massachusetts, New Hampshire, Rhode Island, Vermont
   * New York - Delaware, District of Columbia, Maryland, New Jersey, New York,
   * Pennsylvania, Puerto Rico, U.S. Virgin Islands  Atlanta - Alabama,
   * Florida, Georgia, North Carolina, South Carolina, Virginia, West Virginia
   * Memphis - Arkansas, Kentucky, Louisiana, Mississippi, Tennessee  Chicago -
   * Illinois, Indiana, Michigan, Ohio, Wisconsin   Kansas City - Iowa, Kansas,
   * Minnesota, Missouri, Nebraska, North Dakota, South Dakota  Dallas -
   * Colorado, New Mexico, Oklahoma, Texas  San Francisco - Alaska, American
   * Samoa, Arizona, California, Guam, Hawaii, Idaho, Montana, Nevada, Oregon,
   * States of Micronesia, Utah, Washington, Wyoming
   * @property {string} [fDICREGN] The supervisory FDIC office assigned to the
   * institution.  The eight FDIC Supervisory Regions and their respective
   * states are:    Boston - Connecticut, Maine, Massachusetts, New Hampshire,
   * Rhode Island, Vermont  New York - Delaware, District of Columbia,
   * Maryland, New Jersey, New York, Pennsylvania, Puerto Rico, U.S. Virgin
   * Islands  Atlanta - Alabama, Florida, Georgia, North Carolina, South
   * Carolina, Virginia, West Virginia  Memphis - Arkansas, Kentucky,
   * Louisiana, Mississippi, Tennessee  Chicago - Illinois, Indiana, Michigan,
   * Ohio, Wisconsin   Kansas City - Iowa, Kansas, Minnesota, Missouri,
   * Nebraska, North Dakota, South Dakota  Dallas - Colorado, New Mexico,
   * Oklahoma, Texas  San Francisco - Alaska, American Samoa, Arizona,
   * California, Guam, Hawaii, Idaho, Montana, Nevada, Oregon, States of
   * Micronesia, Utah, Washington, Wyoming
   * @property {string} [fDICSUPV] The supervisory FDIC office assigned to the
   * institution. There are twelve Federal Reserve Districts, with two
   * Districts serving one state in some instances. The list of Federal Reserve
   * Districts and their respective states are as follows: Boston -
   * Connecticut, Maine, Massachuestts, New Hampshire, Rhode Island, Vermont
   * New York - Connecticut, New Jersey, New York, Puerto Rico U.S. Virgin
   * Islands  Phildelphia - Delaware, New Jersey, Pennsylvania Cleveland -
   * Kentucky, Ohio, Pennsylvania, West Virginia Richmond - Maryland, North
   * Carolina, South Carolina, Virginia, West Virginia Atlanta - Alabama,
   * Florida, Georgia, Louisiana, Mississippi, Tennessee Chicago - Illinois,
   * Indiana, Iowa, Michigan, Wisconsin St. Louis - Arkansas, Illinois,
   * Indiana, Kentucky, Mississippi, Missouri, Tennessee Minneapolis -
   * Michigan, Minnesota, Montana, North Dakota, South Dakota, Wisconsin Kansas
   * City - Colorado, Kansas, Missouri, Nebraska, New Mexico, Oklahoma, Wyoming
   * Dallas - Louisiana, New Mexico, Texas San Francisco> - Alaska, American
   * Samoa, Arizona, California, Guam, Hawaii, Idaho, Nevada, Oregon, States of
   * Micronesia, Utah, Washington
   * @property {string} [fED] A number used to identify the Federal Reserve
   * district in which the institution is located. 01 – Boston, 02 - New
   * York,03 – Philadelphia, 04 – Cleveland,05 – Richmond,06 – Atlanta,07 –
   * Chicago,08 - St. Louis,09 – Minneapolis,10 - Kansas city,11 – Dallas,12 -
   * San Francisco
   * @property {string} [fEDRSSD] A unique number assigned by the Federal
   * Reserve board as the entity's unique identifier
   * @property {string} [fEDCHRTR] A flag used to indicate whether the
   * institution is chartered by an agent of the federal government.
   * @property {string} [fLDOFF] The FDIC Field Office where an institution is
   * physically located.
   * @property {string} [fORM31] A flag (1=yes,0=no) that indicates whether and
   * institution filed an FFIEC 031 Call Report. Commercial banks with domestic
   * and foreign offices are required to file such a report.
   * @property {string} [hCTMULT] A flag used to indicate whether an
   * institution is a member of a multibank holding company 1=yes, 0=no
   * @property {string} [iBA] Includes Bank Insurance Fund insured branches in
   * the U.S. established by banks chartered and headquartered in foreign
   * countries.  These institutions are regulated by one of the three Federal
   * commercial bank regulators and submit financial data to the Federal
   * Reserve.
   * @property {string} [iNACTIVE] Institutions that are currently closed but
   * were once insured by the FDIC.
   * @property {string} [iNSAGNT1] Deposit Insurance Fund (DIF), Bank Insurance
   * Fund (BIF), Savings Association Insurance Fund (SAIF)
   * @property {string} [iNSAGNT2] As a result of the establishment of a single
   * Deposit Insurance Fund (DIF) effective April 1, 2006, the Secondary
   * Insurance fund is no longer applicable. previously both bif and saif bank
   * insurance fund - institutions that are members of the bank insurance fund
   * savings association insurance fund - Institutions that are members of the
   * Savings Association Insurance Fund
   * @property {string} [iNSBIF] Institutions who are members of the Bank
   * Insurance Fund. As of April 1, 2006 BIF was merged together with the
   * Savings Institution Insurance Fund (SAIF) to create a single Deposit
   * Insurance Fund (DIF).  All FDIC insured BIF member institutions, that are
   * still active or open, are now insured members of DIF.
   * @property {string} [iNSCOML] Includes commercial banks insured by the
   * FDIC.  These institutions are regulated by one of the three Federal
   * commercial bank regulators (FDIC, Federal Reserve Board, or Office of the
   * Comptroller of the Currency).  They submit financial reports to the
   * Federal Reserve (state member banks) or the FDIC (state non-member banks
   * and national banks).
   * @property {date} [iNSDATE] The date that an institution obtained federal
   * deposit insurance.
   * @property {string} [iNSDIF] A flag used to indicate whether an institution
   * is insured under the Deposit Insurance Fund (DIF).  As of April 1, 2006
   * the Bank Insurance Fund (BIF) was merged together with the Savings
   * Institution Insurance Fund (SAIF) to create a single Deposit Insurance
   * Fund (DIF).  All FDIC insured BIF and SAIF member institutions that are
   * still active or open are now insured members of DIF.    0 = No, not DIF
   * insured and 1 = Yes, DIF insured.  Note that institutions that became
   * inactive prior to April 1006 will also have zero value.
   * @property {string} [iNSFDIC] Includes institutions insured by the FDIC.
   * @property {string} [iNSSAIF] Institutions who are members of the Savings
   * Association Insurance Fund. As of April 1, 2006 SAIF was merged together
   * with the Bank Insurance Fund (BIF) to create a single Deposit Insurance
   * Fund (DIF).  All FDIC insured SAIF member institutions, that are still
   * active or open, are now insured members of DIF.
   * @property {string} [iNSSAVE] Includes savings institutions insured by the
   * FDIC that operate under state or federal banking codes applicable to
   * thrift institutions.  These institutions are regulated by and submit
   * financial reports to one of two Federal regulators (FDIC or Office of
   * Thrift Supervision).
   * @property {string} [iNSTAG] An indicator specifying whether an institution
   * is primarily an agricultural lending institution.
   * @property {string} [iNSTCRCD] Institutions with total loans greater than
   * 50% of total assets and credit card loans greater than 50% of total loans,
   * including loans that have been securitized and sold.
   * @property {string} [lAWSASSERFLG] A flag, yes=1 and no=0 associated with
   * OTS supervised savings associations that converted their charter to that
   * of a commercial or savings bank.  Converted associations remain members of
   * the SAIF, but they become subject to supervision by one of the three
   * federal banking agencies. Not Applicable as of March 31, 2006.
   * @property {string} [mSA] The Metropolitan Statistical Areas based on
   * Census Bureau data, as defined by the US Office of Management (OMB) prior
   * to the year 2000.
   * @property {string} [mSANO] The Metropolitan Statistical Area Number
   * (MSA_NO) in which the institution is physically located.  The Office of
   * Managment and Budget defines MSAs in terms of entire counties surrounding
   * central cities, except in the six New England states where they are
   * defined in terms of cities and towns within counties. Before 200 standards
   * @property {string} [mUTUAL] Banking institutions fall into one of two
   * ownership types, stock or non-stock. An institution which sells stock to
   * raise capital is called a stock institution. It is owned by the
   * shareholders who benefit from profits earned by the institution. A
   * non-stock institution, or mutual institution, is owned and controlled
   * solely by its depositors. A mutual does not issue capital stock.
   * @property {string} [nAME] The legal name of the institution.
   * @property {string} [nAMEHCR] Regulatory top holder is assigned by the
   * Federal Reserve Board based on ownership and control percentages. Note:
   * Information on bank holding companies is only as of quarter-end.
   * Regulatory top holder is any company that directly or indirectly owns,
   * controls or has power to vote 25 percent or more of a bank's or direct
   * holding company's shares or  controls in any manner the election of a
   * majority of the directors or trustees of a bank or direct holding company
   * or  exercises a controlling influence over the management or policies of a
   * bank or direct holding company.   Information on Thrift Holding Companies
   * that own Savings Associations but do not own banks is not currently
   * available in the ID System.  Source:  Federal Reserve Board National
   * Information Center data base.
   * @property {number} [nETINC] Net income. Net interest income plus total
   * noninterest income plus realized gains (losses) on securities and
   * extraordinary items, less total noninterest expense, loan loss provisions
   * and income taxes.
   * @property {number} [nETINCQ] Net income - quarterly. Quarterly net
   * interest income plus total noninterest income plus realized gains (losses)
   * on securities and extraordinary items, less total noninterest expense,
   * loan loss provisions and income taxes.
   * @property {string} [nEWCERT] A new certificate number of an already
   * existing FDIC-insured institution resulting from either a merger or an
   * acquisition.
   * @property {string} [oAKAR] A member of one insurance fund that acquired
   * deposits insured by the other fund, where that portion of the buyer's
   * deposits remained insured by, and assessable by, the other fund.
   * @property {string} [oCCDIST] The Office of the Comptroller of the Currency
   * (OCC) District in which the institution is physically located. The six OCC
   * Districts and their respective states are: Northeast - Connecticut,
   * Delaware, District of Columbia, Maine, Maryland, Massachusetts, New
   * Hampshire, New Jersey, New York, Pennsylvania, Puerto Rico, Rhode Island,
   * Vermont, U.S. Virgin Islands  Southeast - Alabama, Florida, Georgia,
   * Mississippi, North Carolina, South Carolina, Tennessee, Virginia, West
   * Virginia  Central - Illinois, Indiana, Kentucky, Michigan, Ohio, Wisconsin
   * Midwest - Iowa, Kansas, Minnesota, Missouri, Nebraska, North Dakota, South
   * Dakota  Southwest - Arkansas, Louisiana, New Mexico, Oklahoma, Texas  West
   * - Alaska, American Samoa, Arizona, California, Colorado, Guam, Hawaii,
   * Idaho, Montana, Nevada, Oregon, States of Micronesia, Utah, Washington,
   * Wyoming
   * @property {number} [oFFDOM] Number of Domestic Offices. The number of
   * domestic offices (including headquarters) operated by active institutions
   * in the 50 states of the U.S.A.
   * @property {number} [oFFFOR] Number of Foreign Offices. The number of
   * foreign offices (outside the U.S.) operated by the institution.
   * @property {number} [oFFICES] Office. A branch/office is any location, or
   * facility, of a financial institution, including its main office, where
   * deposit accounts are opened, deposits are accepted, checks paid, and loans
   * granted. Some branches include, but are not limited to, brick and mortar
   * locations, detached or attached drive-in facilities, seasonal offices,
   * offices on military bases or government installations, paying/receiving
   * stations or units, nondeposit offices, Internet and PhoneBanking locations
   * where a customer can open accounts, make deposits and borrow money. A
   * branch does not include Automated Teller Machines (ATM), Consumer Credit
   * Offices, Contractual Offices, Customer Bank Communication Terminals
   * (CBCT), Electronic Fund Transfer Units (EFTU), and Loan Production Offices
   * Summary of Deposits information is required for each insured office
   * located in any State, the District of Columbia, the Commonwealth of Puerto
   * Rico or any U.S. territory or possession such as Guam or the U.S. Virgin
   * Islands, without regard to the location of the main office.
   * @property {number} [oFFOA] Number of US Offices. The number of offices
   * operated by an FDIC-insured institution in all commonwealths and
   * terrirtories of the US, along with those in freely associated states under
   * the Compact of Free Association
   * @property {string} [oTSDIST] Office of Thrift Supervision (OTS) District -
   * Sunset (ended)  7/21/11
   * @property {string} [oTSREGNM] Prior to 7/21/11, the Office of Thrift
   * Supervision (OTS) Region in which the institution is physically located.
   * The five OTS Regions and their respective states are: Northeast -
   * Connecticut, Delaware, Maine, Massachusetts, New Hampshire, New Jersey,
   * New York, Pennsylvania, Rhode Island, Vermont, West Virginia Southeast -
   * Alabama, District of Columbia, Florida, Georgia, Maryland, North Carolina,
   * Puerto Rico, South Carolina, U.S. Virgin Islands, Virginia Central -
   * Illinois, Indiana, Kentucky, Michigan, Ohio, Tennessee, Wisconsin Midwest
   * - Arkansas, Colorado, Iowa, Kansas, Louisiana, Minnesota, Mississippi,
   * Missouri, Nebraska, New Mexico, North Dakota, Oklahoma, South Dakota,
   * Texas West - Alaska, American Samoa, Arizona, California, Guam, Hawaii,
   * Idaho, Montana, Nevada, States of Micronesia, Oregon, Utah, Washington,
   * Wyoming
   * @property {string} [pARCERT] The PARCERT number identifies the subsidiary
   * institutions parent certificate number. Beginning in March 1997, both the
   * Thrift Financial Reports and Call Reports are completed on a fully
   * consolidated basis.  Previously, the consolidation of subsidiary
   * depository institutions was prohibited.  Now, parent institutions are
   * required to file consolidated reports, while their subsidiary financial
   * institutions are still required to file separate reports.
   * @property {date} [pROCDATE] A date field indicating the date that a change
   * to this record was processed. Standard format = 'CCYYMMDD' (Length = 8)
   * which has been converted to Month, Day, Year format for display purposes.
   * @property {string} [qBPRCOML] The Quarterly Banking Profile (QBP)
   * Commercial Bank Region in which the institution is physically located.
   * Select from a drop down box. regional breakdown. group data by qbp region
   * is only available for insured commercial banks and insured savings
   * institutions and NOT All Insured Institutions, Insured Commercial Banks by
   * asset size and Insured Savings Institutions by asset size.
   * @property {string} [rEGAGNT] There are four Federal regulators of banks
   * and savings and loan institutions (There are now three federal regulators
   * of banks and savings and loan institutions. Berfore July 21, 2011, there
   * were four federal regulators): federal deposit insurance corporation
   * (fdic) - primary federal regulator responsible for state-chartered banks
   * not members of the Federal Reserve System and state chartered savings
   * banks. Federal Reserve Board (FRB) - Primary Federal regulator responsible
   * for state-chartered commercial bank members of the Federal Reserve System.
   * Office of the Comptroller of the Currency (OCC) - Primary Federal
   * regulator responsible for nationally chartered commercial banks and
   * federally chartered savings and loan associations. Before 7/21/11, Office
   * of Thrift Supervision (OTS) - Primary Federal regulator responsible for
   * federally chartered savings and loan associations, federal savings banks
   * and state-chartered savings and loan associations. FDIC insured depository
   * institutions are members of the Deposit Insurance Fund (DIF).
   * @property {string} [rEGAGENT2] There are four Federal regulators of banks
   * and savings and loan institutions (There are now three federal regulators
   * of banks and savings and loan institutions. Berfore July 21, 2011, there
   * were four federal regulators): federal deposit insurance corporation
   * (fdic) - primary federal regulator responsible for state-chartered banks
   * not members of the Federal Reserve System and state chartered savings
   * banks. Federal Reserve Board (FRB) - Primary Federal regulator responsible
   * for state-chartered commercial bank members of the Federal Reserve System.
   * Office of the Comptroller of the Currency (OCC) - Primary Federal
   * regulator responsible for nationally chartered commercial banks and
   * federally chartered savings and loan associations. Before 7/21/11, Office
   * of Thrift Supervision (OTS) - Primary Federal regulator responsible for
   * federally chartered savings and loan associations, federal savings banks
   * and state-chartered savings and loan associations. FDIC insured depository
   * institutions are members of the Deposit Insurance Fund (DIF).
   * @property {string} [rEPDTE] The last day of the financial reporting period
   * selected.
   * @property {date} [rISDATE] The financial reporting period selected in
   * CCYYMM format.
   * @property {number} [rOA] Return on assets (ROA). Net income after taxes
   * and extraordinary items (annualized) as a percent of average total assets.
   * @property {number} [rOAPTX] Pretax return on assets. Annualized pre-tax
   * net income as a percent of average assets. Note: Includes extraordinary
   * items and other adjustments, net of taxes.
   * @property {number} [rOAPTXQ] Quarterly Pretax return on assets. Quarterly
   * pre-tax net income as a percent of average assets. Note: Includes
   * extraordinary items and other adjustments, net of taxes.
   * @property {number} [rOAQ] Quarterly return on assets. Quarterly net income
   * after taxes and extraordinary items as a percent of average total assets.
   * @property {number} [rOE] Return on Equity (ROE). Annualized net income as
   * a percent of average equity on a consolidated basis.     Note: If retained
   * earnings are  negative, the ratio is shown as NA.
   * @property {number} [rOEQ] Quarterly return on equity. Quarterly net income
   * (including gains or losses on securities and extraordinary items) as a
   * percentage of average total equity capital.
   * @property {string} [rSSDHCR] The unique number assigned by the Federal
   * Reserve Board to the regulatory high holding company of the institution.
   * @property {date} [rUNDATE] The day the institution information was
   * updated.
   * @property {string} [sASSER] OTS supervised savings associations that
   * converted their charter to that of a commercial or savings bank.
   * Converted associations remain members of the SAIF, but they become subject
   * to supervision by one of the three federal banking agencies. Not
   * Applicable as of March 31, 2006.
   * @property {string} [sPECGRP] An indicator of an institution's primary
   * specialization in terms of asset concentration
   * @property {string} [sPECGRPN] Name associated with the numeric indicator
   * (SPECGRP) of an institution's primary specialization in terms of asset
   * concentration
   * @property {string} [sTALP] State in which the the headquarters are
   * physically located. The FDIC Act defines state as any State of the United
   * States, the District of Columbia, and any territory of the United States,
   * Puerto Rico, Guam, American Samoa, the Trust Territory of the Pacific
   * Islands, the Virgin Island, and the Northern Mariana Islands.
   * @property {string} [sTALPHCR] State location of the regulatory high
   * holding company (either direct or indirect owner).
   * @property {string} [sTCHRTR] A flag (1=yes;0=no) that indicates if an
   * institution is state chartered.
   * @property {string} [sTCNTY] A five digit number representing the state and
   * county in which the institution is physically located.  The first two
   * digits represent the FIPS state numeric code and the last three digits
   * represent the FIPS county numeric code.
   * @property {string} [sTMULT] A 'yes' indicates that an institution has
   * branches that can accept FDIC-insured deposits in more than one state.
   * The FDIC Act defines state as any State of the United States, the District
   * of Columbia, and any territory of the United States, Puerto Rico, Guam,
   * American Samoa, the Trust Territory of the Pacific Islands, the Virgin
   * Island, and the Northern Mariana Islands.
   * @property {string} [sTNAME] State in which the the institution is
   * physically located. The FDIC Act defines state as any State of the United
   * States, the District of Columbia, and any territory of the United States,
   * Puerto Rico, Guam, American Samoa, the Trust Territory of the Pacific
   * Islands, the Virgin Island, and the Northern Mariana Islands.
   * @property {string} [sTNUM] The Federal Information Processing Standard
   * code used to identify states
   * @property {string} [sUBCHAPS] The Small Business Job Protection Act of
   * 1996 changed the Internal Revenue Code to allow financial institutions to
   * elect Subchapter S corporation status, beginning in 1997. Banks are
   * required to indicate on the Call Report whether there is currently in
   * effect an election to file under Subchapter S. Thrifts have a similar
   * requirement as of March 1998.  The most important IRS requirements to
   * elect and maintain Subchapter S status are: There can be no more than 75
   * eligible shareholders and no more than one class of stock. (In general,
   * shareholders can only be individuals, estates, and certain types of
   * trusts. Certain retirement plans and charitable organizations will be
   * eligible in 1998.) All shareholders must consent.  Banks and thrifts
   * converting to Subchapter S status must use the specific charge-off method
   * for tax purposes rather than the reserve method of accounting for bad
   * debts and recapture tax bad debt reserves over a period of six years, if
   * the reserve method had been used prior to conversion. (Note: even though
   * the specific charge-off method is required for tax purposes, an adequate
   * allowance for loan and lease losses must still be maintained on the
   * financial statements and Call Reports.) Banks and thrifts are subject to a
   * built-in gains (BIG) tax, if the aggregate fair market value of assets is
   * greater than their aggregate adjusted bases on the date of conversion to
   * Subchapter S status.     [Banks are required to indicate separately on the
   * Call Report in December of each year, the deferred portion of income taxes
   * reported in net income. For Subchapter S banks, some or all of their
   * deferred tax assets and liabilities may be eliminated upon conversion to
   * Subchapter S status; however, deferred taxes related to the BIG tax and
   * the recapture of bad debt reserves must be recognized.].   A Subchapter S
   * corporation is treated as a pass-through entity, similar to a partnership,
   * for federal income tax purposes. It is generally not subject to any
   * federal income taxes at the corporate level. Its taxable income flows
   * through to its shareholders in proportion to their stock ownership, and
   * the shareholders generally pay federal income taxes on their share of this
   * taxable income. This can have the effect of reducing institutions'
   * reported income tax expense and increasing their after-tax earnings..
   * The election of Subchapter S status may result in an increase in
   * shareholders' personal tax liabilities. Therefore, S corporations
   * typically increase the amount of earnings distributed as dividends to
   * compensate for higher personal taxes.
   * @property {string} [sUPRVFD] A numeric value associated with the name of
   * an FDIC supervisory region
   * @property {string} [tE01N528] URL of other public-facing internet web site
   * the reporting institution uses to accept or solicit deposits from the
   * public
   * @property {string} [tE02N528] URL of other public-facing internet web site
   * the reporting institution uses to accept or solicit deposits from the
   * public
   * @property {string} [tE03N528] URL of other public-facing internet web site
   * the reporting institution uses to accept or solicit deposits from the
   * public
   * @property {string} [tE04N528] URL of other public-facing internet web site
   * the reporting institution uses to accept or solicit deposits from the
   * public
   * @property {string} [tE05N528] URL of other public-facing internet web site
   * the reporting institution uses to accept or solicit deposits from the
   * public
   * @property {string} [tE06N528] URL of other public-facing internet web site
   * the reporting institution uses to accept or solicit deposits from the
   * public
   * @property {string} [tE07N528] URL of other public-facing internet web site
   * the reporting institution uses to accept or solicit deposits from the
   * public
   * @property {string} [tE08N528] URL of other public-facing internet web site
   * the reporting institution uses to accept or solicit deposits from the
   * public
   * @property {string} [tE09N528] URL of other public-facing internet web site
   * the reporting institution uses to accept or solicit deposits from the
   * public
   * @property {string} [tE10N528] URL of other public-facing internet web site
   * the reporting institution uses to accept or solicit deposits from the
   * public
   * @property {string} [tE01N529] Trade name other than the institution's
   * legal name used to identify one of the institution's physical offices at
   * which deposits are accepted or solicited from the public
   * @property {string} [tE02N529] Trade name other than the institution's
   * legal name used to identify one of the institution's physical offices at
   * which deposits are accepted or solicited from the public
   * @property {string} [tE03N529] Trade name other than the institution's
   * legal name used to identify one of the institution's physical offices at
   * which deposits are accepted or solicited from the public
   * @property {string} [tE04N529] Trade name other than the institution's
   * legal name used to identify one of the institution's physical offices at
   * which deposits are accepted or solicited from the public
   * @property {string} [tE05N529] Trade name other than the institution's
   * legal name used to identify one of the institution's physical offices at
   * which deposits are accepted or solicited from the public
   * @property {string} [tE06N529] Trade name other than the institution's
   * legal name used to identify one of the institution's physical offices at
   * which deposits are accepted or solicited from the public
   * @property {string} [tRACT] Beyond having trust powers granted and
   * exercised, institutions with fiduciary assets accounts, income, or other
   * reportable fiduciary related service
   * @property {string} [tRUST] A flag used to indicate an institution's Trust
   * Powers Granted status. 0 = No Trust Power Granted 1 = Trust Power Granted
   * Where Trust Power has been granted specific codes are: 00 - Trust powers
   * not know 10 - Full trust powers granted 11 - Full trust powers granted,
   * exercised 12 - Full trust powers granted, not exercised 20 - Limited trust
   * powers granted 21 - Limited trust powers granted, exercised 22 - Limited
   * trust powers granted, not exercised 30 - Trust powers not granted 31 -
   * Trust powers not granted, but exercised
   * @property {string} [uLTCERT] The cert number of the last successor or
   * acquirer of the institution
   * @property {string} [uNINUM] FDIC's unique identifier number for holding
   * companies, banks, branches and nondeposit subsidiaries.
   * @property {string} [wEBADDR] The primary internet web address is the
   * public internet site obtained from the most recent FFIEC Call Report
   * (CALL) for commercial banks or from the supplemental information for
   * Thrift Financial Reporters (TFR). The primary internet web address is
   * included only for those institutions reporting an address on the most
   * recent FFIEC Call Report or Thrift Financial Report.  This information
   * resides in the most recent demographic information file. For some
   * institutions users will find that for the item Primary Internet Web
   * Address: the caption will read 'Web site not available'.  Possible reasons
   * that a Web site may not be available are: The institution failed to file
   * on the most recent call report or TFR. The institution filed a primary
   * Internet Web address on its most recent FFIEC Call Report; however, the
   * address filed by the institution was not in accordance with the
   * instructions provided by the FFIEC on how to file a primary Internet Web
   * address or FDIC attempts to validate and access the site were
   * unsuccessful. Users may also experience instances where the URL provided
   * for primary Internet Web address in ID returns an error stating that the
   * site is not found. Possible reasons for such occurrences are: The
   * institution?s reported primary Web address was valid as of the date that
   * the demographic information was updated in ID, but is no longer valid. The
   * institution?s reported Internet Web address is valid, but the
   * institution?s Web site was inoperable at the time that the user attempted
   * to access it due to technical problems being experienced by the
   * institution?s Web site, the institution?s web provider, the user?s Web
   * provider, or other issues not related to the validity of the Web address.
   * Users are advised to contact the institution on any questions regarding
   * the services provided by the institution. For questions involving the
   * reporting of primary Internet Web address by those institutions that file
   * a FFIEC Call report, users are advised to contact supervision@fdic.gov.
   * For questions involving the primary Internet Web address of institutions
   * that file a Thrift Financial Report, users are advised to contact
   * pamela.schaar@ots.treas.gov or call Ms. Schaar at (202) 906-7205.
   * Disclaimer: The Primary Internet Web Addresses listed have been reported
   * to the FDIC by each institution. The hyperlinks to institution Internet
   * sites are provided solely as a convenience to users of the FDIC Internet
   * site. The FDIC has made a limited effort to determine that these links
   * function properly. However, linked sites are not under the control of
   * FDIC, and FDIC is not responsible for the contents of any linked site, or
   * any link contained in a linked site.  Even if you access an institution?s
   * site by means of the link provided by FDIC, you are responsible for
   * confirming the identity and authenticity of any institution you visit and
   * transact business with online. The inclusion of a link does not imply or
   * constitute an endorsement by FDIC of the institution, its ownership or
   * management, the products or services it offers, or any advertisers or
   * sponsors appearing on the institution?s web site.
   * @property {string} [zIP] The first three, four, or five digits of the full
   * postal zip code representing physical location of the institution or its
   * branch office.
   */
  constructor() {
  }

  /**
   * Defines the metadata of InstitutionData
   *
   * @returns {object} metadata of InstitutionData
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'institution-data',
      type: {
        name: 'Composite',
        className: 'InstitutionData',
        modelProperties: {
          aCTIVE: {
            required: false,
            serializedName: 'ACTIVE',
            type: {
              name: 'String'
            }
          },
          aDDRESS: {
            required: false,
            serializedName: 'ADDRESS',
            type: {
              name: 'String'
            }
          },
          aSSET: {
            required: false,
            serializedName: 'ASSET',
            type: {
              name: 'Number'
            }
          },
          bKCLASS: {
            required: false,
            serializedName: 'BKCLASS',
            type: {
              name: 'String'
            }
          },
          cb: {
            required: false,
            serializedName: 'CB',
            type: {
              name: 'String'
            }
          },
          cBSA: {
            required: false,
            serializedName: 'CBSA',
            type: {
              name: 'String'
            }
          },
          cBSADIV: {
            required: false,
            serializedName: 'CBSA_DIV',
            type: {
              name: 'String'
            }
          },
          cBSADIVFLG: {
            required: false,
            serializedName: 'CBSA_DIV_FLG',
            type: {
              name: 'String'
            }
          },
          cBSADIVNO: {
            required: false,
            serializedName: 'CBSA_DIV_NO',
            type: {
              name: 'String'
            }
          },
          cBSAMETRO: {
            required: false,
            serializedName: 'CBSA_METRO',
            type: {
              name: 'String'
            }
          },
          cBSAMETROFLG: {
            required: false,
            serializedName: 'CBSA_METRO_FLG',
            type: {
              name: 'String'
            }
          },
          cBSAMETRONAME: {
            required: false,
            serializedName: 'CBSA_METRO_NAME',
            type: {
              name: 'String'
            }
          },
          cBSAMICROFLG: {
            required: false,
            serializedName: 'CBSA_MICRO_FLG',
            type: {
              name: 'String'
            }
          },
          cBSANO: {
            required: false,
            serializedName: 'CBSA_NO',
            type: {
              name: 'String'
            }
          },
          cERT: {
            required: false,
            serializedName: 'CERT',
            type: {
              name: 'String'
            }
          },
          cERTCONS: {
            required: false,
            serializedName: 'CERTCONS',
            type: {
              name: 'String'
            }
          },
          cFPBEFFDTE: {
            required: false,
            serializedName: 'CFPBEFFDTE',
            type: {
              name: 'DateTime'
            }
          },
          cFPBENDDTE: {
            required: false,
            serializedName: 'CFPBENDDTE',
            type: {
              name: 'DateTime'
            }
          },
          cFPBFLAG: {
            required: false,
            serializedName: 'CFPBFLAG',
            type: {
              name: 'String'
            }
          },
          cHANGEC1: {
            required: false,
            serializedName: 'CHANGEC1',
            type: {
              name: 'String'
            }
          },
          cHANGEC2: {
            required: false,
            serializedName: 'CHANGEC2',
            type: {
              name: 'String'
            }
          },
          cHANGEC3: {
            required: false,
            serializedName: 'CHANGEC3',
            type: {
              name: 'String'
            }
          },
          cHANGEC4: {
            required: false,
            serializedName: 'CHANGEC4',
            type: {
              name: 'String'
            }
          },
          cHANGEC5: {
            required: false,
            serializedName: 'CHANGEC5',
            type: {
              name: 'String'
            }
          },
          cHARTER: {
            required: false,
            serializedName: 'CHARTER',
            type: {
              name: 'String'
            }
          },
          cHRTAGNT: {
            required: false,
            serializedName: 'CHRTAGNT',
            type: {
              name: 'String'
            }
          },
          cITY: {
            required: false,
            serializedName: 'CITY',
            type: {
              name: 'String'
            }
          },
          cITYHCR: {
            required: false,
            serializedName: 'CITYHCR',
            type: {
              name: 'String'
            }
          },
          cLCODE: {
            required: false,
            serializedName: 'CLCODE',
            type: {
              name: 'String'
            }
          },
          cMSANO: {
            required: false,
            serializedName: 'CMSA_NO',
            type: {
              name: 'String'
            }
          },
          cMSA: {
            required: false,
            serializedName: 'CMSA',
            type: {
              name: 'String'
            }
          },
          cONSERVE: {
            required: false,
            serializedName: 'CONSERVE',
            type: {
              name: 'String'
            }
          },
          cOUNTY: {
            required: false,
            serializedName: 'COUNTY',
            type: {
              name: 'String'
            }
          },
          cSA: {
            required: false,
            serializedName: 'CSA',
            type: {
              name: 'String'
            }
          },
          cSANO: {
            required: false,
            serializedName: 'CSA_NO',
            type: {
              name: 'String'
            }
          },
          cSAFLG: {
            required: false,
            serializedName: 'CSA_FLG',
            type: {
              name: 'String'
            }
          },
          dATEUPDT: {
            required: false,
            serializedName: 'DATEUPDT',
            type: {
              name: 'String'
            }
          },
          dENOVO: {
            required: false,
            serializedName: 'DENOVO',
            type: {
              name: 'String'
            }
          },
          dEP: {
            required: false,
            serializedName: 'DEP',
            type: {
              name: 'Number'
            }
          },
          dEPDOM: {
            required: false,
            serializedName: 'DEPDOM',
            type: {
              name: 'Number'
            }
          },
          dOCKET: {
            required: false,
            serializedName: 'DOCKET',
            type: {
              name: 'String'
            }
          },
          eFFDATE: {
            required: false,
            serializedName: 'EFFDATE',
            type: {
              name: 'DateTime'
            }
          },
          eNDEFYMD: {
            required: false,
            serializedName: 'ENDEFYMD',
            type: {
              name: 'String'
            }
          },
          eq: {
            required: false,
            serializedName: 'EQ',
            type: {
              name: 'String'
            }
          },
          eSTYMD: {
            required: false,
            serializedName: 'ESTYMD',
            type: {
              name: 'DateTime'
            }
          },
          fDICDBS: {
            required: false,
            serializedName: 'FDICDBS',
            type: {
              name: 'String'
            }
          },
          fDICREGN: {
            required: false,
            serializedName: 'FDICREGN',
            type: {
              name: 'String'
            }
          },
          fDICSUPV: {
            required: false,
            serializedName: 'FDICSUPV',
            type: {
              name: 'String'
            }
          },
          fED: {
            required: false,
            serializedName: 'FED',
            type: {
              name: 'String'
            }
          },
          fEDRSSD: {
            required: false,
            serializedName: 'FED_RSSD',
            type: {
              name: 'String'
            }
          },
          fEDCHRTR: {
            required: false,
            serializedName: 'FEDCHRTR',
            type: {
              name: 'String'
            }
          },
          fLDOFF: {
            required: false,
            serializedName: 'FLDOFF',
            type: {
              name: 'String'
            }
          },
          fORM31: {
            required: false,
            serializedName: 'FORM31',
            type: {
              name: 'String'
            }
          },
          hCTMULT: {
            required: false,
            serializedName: 'HCTMULT',
            type: {
              name: 'String'
            }
          },
          iBA: {
            required: false,
            serializedName: 'IBA',
            type: {
              name: 'String'
            }
          },
          iNACTIVE: {
            required: false,
            serializedName: 'INACTIVE',
            type: {
              name: 'String'
            }
          },
          iNSAGNT1: {
            required: false,
            serializedName: 'INSAGNT1',
            type: {
              name: 'String'
            }
          },
          iNSAGNT2: {
            required: false,
            serializedName: 'INSAGNT2',
            type: {
              name: 'String'
            }
          },
          iNSBIF: {
            required: false,
            serializedName: 'INSBIF',
            type: {
              name: 'String'
            }
          },
          iNSCOML: {
            required: false,
            serializedName: 'INSCOML',
            type: {
              name: 'String'
            }
          },
          iNSDATE: {
            required: false,
            serializedName: 'INSDATE',
            type: {
              name: 'DateTime'
            }
          },
          iNSDIF: {
            required: false,
            serializedName: 'INSDIF',
            type: {
              name: 'String'
            }
          },
          iNSFDIC: {
            required: false,
            serializedName: 'INSFDIC',
            type: {
              name: 'String'
            }
          },
          iNSSAIF: {
            required: false,
            serializedName: 'INSSAIF',
            type: {
              name: 'String'
            }
          },
          iNSSAVE: {
            required: false,
            serializedName: 'INSSAVE',
            type: {
              name: 'String'
            }
          },
          iNSTAG: {
            required: false,
            serializedName: 'INSTAG',
            type: {
              name: 'String'
            }
          },
          iNSTCRCD: {
            required: false,
            serializedName: 'INSTCRCD',
            type: {
              name: 'String'
            }
          },
          lAWSASSERFLG: {
            required: false,
            serializedName: 'LAW_SASSER_FLG',
            type: {
              name: 'String'
            }
          },
          mSA: {
            required: false,
            serializedName: 'MSA',
            type: {
              name: 'String'
            }
          },
          mSANO: {
            required: false,
            serializedName: 'MSA_NO',
            type: {
              name: 'String'
            }
          },
          mUTUAL: {
            required: false,
            serializedName: 'MUTUAL',
            type: {
              name: 'String'
            }
          },
          nAME: {
            required: false,
            serializedName: 'NAME',
            type: {
              name: 'String'
            }
          },
          nAMEHCR: {
            required: false,
            serializedName: 'NAMEHCR',
            type: {
              name: 'String'
            }
          },
          nETINC: {
            required: false,
            serializedName: 'NETINC',
            type: {
              name: 'Number'
            }
          },
          nETINCQ: {
            required: false,
            serializedName: 'NETINCQ',
            type: {
              name: 'Number'
            }
          },
          nEWCERT: {
            required: false,
            serializedName: 'NEWCERT',
            type: {
              name: 'String'
            }
          },
          oAKAR: {
            required: false,
            serializedName: 'OAKAR',
            type: {
              name: 'String'
            }
          },
          oCCDIST: {
            required: false,
            serializedName: 'OCCDIST',
            type: {
              name: 'String'
            }
          },
          oFFDOM: {
            required: false,
            serializedName: 'OFFDOM',
            type: {
              name: 'Number'
            }
          },
          oFFFOR: {
            required: false,
            serializedName: 'OFFFOR',
            type: {
              name: 'Number'
            }
          },
          oFFICES: {
            required: false,
            serializedName: 'OFFICES',
            type: {
              name: 'Number'
            }
          },
          oFFOA: {
            required: false,
            serializedName: 'OFFOA',
            type: {
              name: 'Number'
            }
          },
          oTSDIST: {
            required: false,
            serializedName: 'OTSDIST',
            type: {
              name: 'String'
            }
          },
          oTSREGNM: {
            required: false,
            serializedName: 'OTSREGNM',
            type: {
              name: 'String'
            }
          },
          pARCERT: {
            required: false,
            serializedName: 'PARCERT',
            type: {
              name: 'String'
            }
          },
          pROCDATE: {
            required: false,
            serializedName: 'PROCDATE',
            type: {
              name: 'DateTime'
            }
          },
          qBPRCOML: {
            required: false,
            serializedName: 'QBPRCOML',
            type: {
              name: 'String'
            }
          },
          rEGAGNT: {
            required: false,
            serializedName: 'REGAGNT',
            type: {
              name: 'String'
            }
          },
          rEGAGENT2: {
            required: false,
            serializedName: 'REGAGENT2',
            type: {
              name: 'String'
            }
          },
          rEPDTE: {
            required: false,
            serializedName: 'REPDTE',
            type: {
              name: 'String'
            }
          },
          rISDATE: {
            required: false,
            serializedName: 'RISDATE',
            type: {
              name: 'DateTime'
            }
          },
          rOA: {
            required: false,
            serializedName: 'ROA',
            type: {
              name: 'Number'
            }
          },
          rOAPTX: {
            required: false,
            serializedName: 'ROAPTX',
            type: {
              name: 'Number'
            }
          },
          rOAPTXQ: {
            required: false,
            serializedName: 'ROAPTXQ',
            type: {
              name: 'Number'
            }
          },
          rOAQ: {
            required: false,
            serializedName: 'ROAQ',
            type: {
              name: 'Number'
            }
          },
          rOE: {
            required: false,
            serializedName: 'ROE',
            type: {
              name: 'Number'
            }
          },
          rOEQ: {
            required: false,
            serializedName: 'ROEQ',
            type: {
              name: 'Number'
            }
          },
          rSSDHCR: {
            required: false,
            serializedName: 'RSSDHCR',
            type: {
              name: 'String'
            }
          },
          rUNDATE: {
            required: false,
            serializedName: 'RUNDATE',
            type: {
              name: 'DateTime'
            }
          },
          sASSER: {
            required: false,
            serializedName: 'SASSER',
            type: {
              name: 'String'
            }
          },
          sPECGRP: {
            required: false,
            serializedName: 'SPECGRP',
            type: {
              name: 'String'
            }
          },
          sPECGRPN: {
            required: false,
            serializedName: 'SPECGRPN',
            type: {
              name: 'String'
            }
          },
          sTALP: {
            required: false,
            serializedName: 'STALP',
            type: {
              name: 'String'
            }
          },
          sTALPHCR: {
            required: false,
            serializedName: 'STALPHCR',
            type: {
              name: 'String'
            }
          },
          sTCHRTR: {
            required: false,
            serializedName: 'STCHRTR',
            type: {
              name: 'String'
            }
          },
          sTCNTY: {
            required: false,
            serializedName: 'STCNTY',
            type: {
              name: 'String'
            }
          },
          sTMULT: {
            required: false,
            serializedName: 'STMULT',
            type: {
              name: 'String'
            }
          },
          sTNAME: {
            required: false,
            serializedName: 'STNAME',
            type: {
              name: 'String'
            }
          },
          sTNUM: {
            required: false,
            serializedName: 'STNUM',
            type: {
              name: 'String'
            }
          },
          sUBCHAPS: {
            required: false,
            serializedName: 'SUBCHAPS',
            type: {
              name: 'String'
            }
          },
          sUPRVFD: {
            required: false,
            serializedName: 'SUPRV_FD',
            type: {
              name: 'String'
            }
          },
          tE01N528: {
            required: false,
            serializedName: 'TE01N528',
            type: {
              name: 'String'
            }
          },
          tE02N528: {
            required: false,
            serializedName: 'TE02N528',
            type: {
              name: 'String'
            }
          },
          tE03N528: {
            required: false,
            serializedName: 'TE03N528',
            type: {
              name: 'String'
            }
          },
          tE04N528: {
            required: false,
            serializedName: 'TE04N528',
            type: {
              name: 'String'
            }
          },
          tE05N528: {
            required: false,
            serializedName: 'TE05N528',
            type: {
              name: 'String'
            }
          },
          tE06N528: {
            required: false,
            serializedName: 'TE06N528',
            type: {
              name: 'String'
            }
          },
          tE07N528: {
            required: false,
            serializedName: 'TE07N528',
            type: {
              name: 'String'
            }
          },
          tE08N528: {
            required: false,
            serializedName: 'TE08N528',
            type: {
              name: 'String'
            }
          },
          tE09N528: {
            required: false,
            serializedName: 'TE09N528',
            type: {
              name: 'String'
            }
          },
          tE10N528: {
            required: false,
            serializedName: 'TE10N528',
            type: {
              name: 'String'
            }
          },
          tE01N529: {
            required: false,
            serializedName: 'TE01N529',
            type: {
              name: 'String'
            }
          },
          tE02N529: {
            required: false,
            serializedName: 'TE02N529',
            type: {
              name: 'String'
            }
          },
          tE03N529: {
            required: false,
            serializedName: 'TE03N529',
            type: {
              name: 'String'
            }
          },
          tE04N529: {
            required: false,
            serializedName: 'TE04N529',
            type: {
              name: 'String'
            }
          },
          tE05N529: {
            required: false,
            serializedName: 'TE05N529',
            type: {
              name: 'String'
            }
          },
          tE06N529: {
            required: false,
            serializedName: 'TE06N529',
            type: {
              name: 'String'
            }
          },
          tRACT: {
            required: false,
            serializedName: 'TRACT',
            type: {
              name: 'String'
            }
          },
          tRUST: {
            required: false,
            serializedName: 'TRUST',
            type: {
              name: 'String'
            }
          },
          uLTCERT: {
            required: false,
            serializedName: 'ULTCERT',
            type: {
              name: 'String'
            }
          },
          uNINUM: {
            required: false,
            serializedName: 'UNINUM',
            type: {
              name: 'String'
            }
          },
          wEBADDR: {
            required: false,
            serializedName: 'WEBADDR',
            type: {
              name: 'String'
            }
          },
          zIP: {
            required: false,
            serializedName: 'ZIP',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = InstitutionData;
