/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Metadata.
 */
class Metadata {
  /**
   * Create a Metadata.
   * @property {number} [total] Total query result count
   * @property {object} [parameters] Query parameters supplied
   * @property {object} [index]
   * @property {string} [index.name] name of index used to retrieve data
   * @property {date} [index.createTimestamp] date/time index was created
   */
  constructor() {
  }

  /**
   * Defines the metadata of Metadata
   *
   * @returns {object} metadata of Metadata
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'metadata',
      type: {
        name: 'Composite',
        className: 'Metadata',
        modelProperties: {
          total: {
            required: false,
            serializedName: 'total',
            type: {
              name: 'Number'
            }
          },
          parameters: {
            required: false,
            serializedName: 'parameters',
            type: {
              name: 'Object'
            }
          },
          index: {
            required: false,
            serializedName: 'index',
            type: {
              name: 'Composite',
              className: 'MetadataIndex'
            }
          }
        }
      }
    };
  }
}

module.exports = Metadata;
