/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Summary.
 */
class Summary {
  /**
   * Create a Summary.
   * @property {object} [data]
   * @property {number} [data.aLLOTHER] All Other Loans
   * @property {number} [data.alsonew] New savings institution charter created
   * to absorb any other type of charter in its first quarter of operation.
   * @property {number} [data.aSSET] Total Assets On A Consolidated Basis
   * Note: For Banks With Foreign Operations Data For March &
   * September Of 1973 Through 1975 Are Reported On A
   * Domestic Basis
   * @property {number} [data.bANKS] Total Insured Commercial Banks filing
   * 12/31 fincncial report  (See Notes to User for definition of commercial
   * bank)
   * @property {number} [data.bKPREM] Premises And Fixed Assets
   * Note:
   * (1) Premises And Fixed Assets (Including Capitalized Leases) On A
   * Consolidated Basis
   * (2) For Banks With Foreign Operations Data For March & September Of 1972
   * Through 1975 Was Reported On A Domestic Basis
   * @property {number} [data.bRANCHES] Branches include all offices of a bank,
   * other than its head office, at which deposits are received, checks paid or
   * money lent. Banking facilities separate from a banking house, banking
   * facilities at government installations, offices, agencies, paying or
   * receiving stations, drive-in facilities and other facilities operated for
   * limited purposes are defined as branches under the FDI Act (see Notes to
   * User)
   * @property {number} [data.bRANCHIN] Banks with branches are institutions
   * that operate one or more offices at which deposits are received or other
   * banking business conducted in addition to the main or head office.
   * @property {number} [data.bRO] Borrowed Deposits (Represents funds which
   * the reporting bank obtains, directly or indirectly, by or through any
   * deposit broker for deposit into one or more deposit accounts. Includes
   * both those in which the entire beneficial interest in a given bank deposit
   * account or investment is held by a single depositor and those in which
   * deposit broker sells participation in a given bank deposit account or
   * instrument to one or more investors).
   * @property {number} [data.bRWDMONY] Borrowed Funds - (1969-Present --
   * Represents Federal Funds purchase. securities sold under agreements to
   * repurchase, demand notes issued to the US Treasury, mortgage indebtedness,
   * liabilities under capitalized leases and all other liabilities for
   * borrowed money. -- 1934-1968 -- Does not include mortgage indebtedness
   * which is netted against bank premsises.)
   * @property {string} [data.cbSI] Differentiates the summarised data between
   * the Commercial Banks and the Savings Institutions. Possible values
   * include: 'CB', 'SI'
   * @property {number} [data.chartoth] Represents the transfer of a commercial
   * bank to a savings institution charter that meets the definition of a
   * thrift (see Notes to Table SI-1) and has applied for and received FDIC
   * insurance (BIF or SAIF).
   * @property {number} [data.cHBAL] Total Cash And Balances Due From
   * Depository Institutions Which Include Both Noninterest-Bearing And
   * Interest-Bearing Deposits On A Consolidated Basis
   * Note:
   * (1): Additional Detail Can Be Found On Schedule Rc-A
   * (2) For Banks With Foreign Operations Data For March And September 1972
   * Through 1975 Are Reported On A Domestic Basis
   * @property {number} [data.cHBALI] Interest-Bearing Balances Due From
   * Depository Institutions On A Consolidated Basis
   * Note: Additional Detail Can Be Found On Schedule Rc-A
   * @property {number} [data.chrtrest] Represents the transfer of an existing
   * institution that does not have deposit insurance to a savings institution
   * charter with FDIC insurance from BIF or SAIF. Examples of such
   * institutions include Trust Banks and savings institutions with state
   * deposit insurance that apply for and receive FDIC insurance
   * @property {number} [data.comboass] Represents the absorption of a failing
   * savings institution by another savings institution with assistance from
   * either the BIF or SAIF. (Included are RTC Accelerated Resolution Program
   * (ARP) assisted mergers. These institutions were not placed in RTC
   * conservatorship.)
   * @property {number} [data.combos] Represents the absorption of a savings
   * institution charter by another savings institution without assistance.
   * Both institutions may be owned by the same holding company in a
   * consolidation of affiliates.
   * @property {number} [data.cONS] Institutions in RTC Conservatorship
   * @property {number} [data.cORPBNDS] Other Debt Securities
   * @property {number} [data.cOUNT] All FDIC Insured Savings Institutions
   * filing a 12/31 financial report
   * @property {number} [data.cRLNLS] Total Recoveries Of Loans And Lease
   * Financing Receivables Credited To The Allowance For Loan And Lease Losses
   * Note: For Banks With Foreign Operations, Data For December
   * 1972 Through December 1975 Are Domestic Only
   * @property {number} [data.dDT] Total Demand Deposits Included In Total
   * Transaction Accounts Held In Domestic Offices
   * Note: For Tfr Filers Between June 1989 Through March 1990 Includes
   * Non-Interest Bearing Deposits
   * @property {number} [data.dEP] Total Deposits On A Consolidated Basis
   * Note:
   * (1) Additional Detail Can Be Found On Schedule Rc-E
   * (2) For Banks With Foreign Operations Data For March & September Of 1972
   * Through 1975 Are Reported On A Domestic Basis
   * @property {number} [data.dEPDOM] Represents the sum of total deposits,
   * domestic offices only
   * @property {number} [data.dEPFOR] Represents the sum of total deposits in
   * foreign offices
   * @property {number} [data.dEPI] Interest-Bearing Consolidated Office
   * Deposits
   *
   * Note:
   * (1) Additional Detail Can Be Found On Schedule Rc-E
   * (2) Tfr Filers With Less Than $300 Million In Assets And Risk-Based
   * Capital Ratios In Excess Of 12 Percent Are Not Required To File Schedule
   * Cmr Beginning March 1993, However, When Cmr Data Is Either Incorrect Or
   * Not Filed Fts Assumes That All Deposits Are Interest-Bearing
   * (3) Prior To Receipt Of The 75-Day Tfr Tape All Tfr Filers Deposits Are
   * Assumed To Be Interest-Bearing
   * (4) For Banks With Foreign Operations Data For March & September Of 1972
   * Through 1975 Are Reported On A Domestic Basis
   * @property {number} [data.dEPIFOR] Represents any deposit in foreign
   * offices, whether demand, savings or time, on which the bank pays or
   * accrues interest
   * @property {number} [data.dEPNI] Represents any deposit on which the bank
   * does not pay or accrue interest
   * @property {number} [data.dEPNIFOR] Represents any deposit in foreign
   * offices on which the bank does not pay or accrue interest
   * @property {number} [data.dRLNLS] Total Charged-Off Loans And Lease
   * Financing Receivables Debited To The Allowance For Loan And Lease Losses
   * Note: For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.eAMINTAN] Goodwill Impairment Losses And
   * Amortization Expense And Impairment Loss For Other Intangible Assets On A
   * Consolidated Basis
   *
   * Note:
   * (1) Prior To March 2001, Listed As Memoranda Only And Is Included In All
   * Other Noninterest Expense
   * (2) Includes Only Amortization Of Goodwill For Tfr Filers
   * @property {number} [data.eDEP] Interest Expense On Total Deposits
   * (Domestic And Foreign) On A Consolidated Basis
   * Note: For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.eDEPDOM] Interest Expense On Total Deposits Held
   * In Domestic Offices
   * Note: For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.eDEPFOR] Deposit Interest Expense-For
   * (1976-Present -- Represents all interests on all liabilities reportable as
   * deposits in foreign offices. -- 1934-1975 -- Interest on foregin office
   * deposits is not available. Reports of income were submitted on a domestic
   * only basis.)
   * @property {number} [data.eEREPP] Represents the gross expenses of all
   * liabilities reportable under this category
   * @property {number} [data.eFHLBADV] Interest Expense And The Amortization
   * Of Any Related Yield Adjustments On Fhlbank Advances
   * Note: Only Reported By Tfr Filers
   * @property {number} [data.eFREPP] Interest Expense On Federal Funds
   * Purchased And Securities Sold Under Agreements To Repurchase On A
   * Consolidated Basis (Prior To March 1997 Was On A Consolidated Basis In
   * Domestic Offices Of The Bank And Of Its Edge And Agreement Subsidiaries,
   * And In Ibf'S)
   * Note: For Banks With Foreign Operations, Data For December
   * 1972 Through December 1975 Are Domestic Only
   * @property {number} [data.eINTEXP] Total Interest Expense On A Consolidated
   * Basis
   * Note: For Banks With Foreign Operations, Data For December
   * 1972 Through December 1975 Are Domestic Only
   * @property {number} [data.eINTEXP2] Eintexp2
   * @property {number} [data.eLNATR] Provision For Loan & Lease Losses On A
   * Consolidated Basis
   *
   * Note:
   * (1) Beginning March 2003, Includes The Provision For Allocated Transfer
   * Risk Related To Loans
   * (2) From March 1997 To December 2000, Defined As The Provision For Credit
   * Losses & Allocated Transfer Risk Reserve Which Includes The Provision For
   * Off-Balance Sheet Credit Losses For Call Report Filers
   * (3) Prior To March 1997, Defined As The Provision For Loan And Lease
   * Losses & Allocated Transfer Risk
   * (4) For Tfr Filers, Consists Of The Provision For Loan And Lease Losses
   * (5) Reflects Net Provision For Losses On Interest-Bearing Assets For Tfr
   * Filers
   * (6) For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.eOTHNINT] All Other Noninterest Expense On A
   * Consolidated Basis
   *
   * Note:
   * (1) Prior To March 2001, Included The Amortization Of Intangible Assets
   * For Call Reporters
   * (2) Greater Detail Is Provided In Subsequent Data Fields For All Items In
   * Excess Of 10% Of This Item All Other Noninterest Expense On A Consolidated
   * Basis
   * (3) Does Not Include Losses On Asset Sales For Tfr Filers Beginning June
   * 1996, Such Gains (Losses) Are Included Net In Noninterest Income
   * (4) Includes Loss On Sale Of Securities Held For Investments For Tfr
   * Filers Between March 1984 Through December 1986
   * (5) For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.ePREMAGG] Expenses Of Premises And Fixed Assets
   * (Net Of Rental Income And Excluding Salaries And Employee Benefits And
   * Mortgage Interest) On A Consolidated Basis
   * Note: For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.eq] Represents the sum of all capital accounts
   * @property {number} [data.eQCDIV] Cash Dividends Declared On Common And
   * Preferred Stock On A Consolidated Basis
   * Note: For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.eQCDIVC] Cash Dividends Declared On Common Stock
   * On A Consolidated Basis
   *
   * Note:
   * (1) 034 Reporters Only File Data On The December Call
   * (2) For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.eQCDIVP] Cash Dividends Declared On Preferred
   * Stock On A Consolidated Basis
   * Note:
   * (1) 034 Reporters Only File Data On The December Call
   * (2) For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.eQCS] Common Stock On A Consolidated Basis
   * Note: For Banks With Foreign Operations, Data For March & September Of
   * 1972 Through 1975 Are Reported On A Domestic Basis
   * @property {number} [data.eQDIV] The total of cash dividends declared on
   * all preferred and common stock during the calendar year, regardless of
   * when payable
   * @property {number} [data.eQNM] Total Capital (Represents the total of all
   * capital components, including FDIC net worth certificates.)
   * @property {number} [data.eQNWCERT] Net Worth Certificates Represents The
   * Outstanding Balances Issued To The Fdic In Exchange For Promissory Notes
   * Received From The Fdic On A Consolidated Basis
   * @property {number} [data.eQOTHCC] (CB) Other Capital
   * @property {number} [data.eQPP] Perpetual Preferred Stock And Related
   * Surplus On A Consolidated Basis
   * Note: For Banks With Foreign Operations, Data For March & September Of
   * 1972 Through 1975 Are Reported On A Domestic Basis
   * @property {number} [data.eQSUR] Surplus (Excludes All Surplus Related To
   * Preferred Stock) On A Consolidated Basis
   * Note: For Banks With Foreign Operations, Data For March & September Of
   * 1972 Through 1975 Are Reported On A Domestic Basis
   * @property {number} [data.eQUPTOT] Undivided Profits, Capital Reserves, Net
   * Unrealized Holding Gains (Losses) On Available-For-Sale Securities And
   * Other Equity Capital Components And/Or
   * Accumulated Gains (Losses) On Cash Flow Hedges On A Consolidated Basis
   *
   * Note:
   * (1) Prior To March 1999 Included Undivided Profits, Capital Reserves And
   * Net Unrealized Gains (Losses) On Available-For-Sale Securities
   * (2) Prior To March 1994 Included Undivided Profits And Capital Reserves
   * Less Net Unrealized Loss On Marketable Equity Securities
   * (3) This Item Includes Net Worth Certificates For Bif Thrifts
   * (4) For Banks With Foreign Operations, Data For March & September Of 1972
   * Through 1975 Are Reported On A Domestic Basis
   * @property {number} [data.eSAL] Salaries And Employee Benefits On A
   * Consolidated Basis Note: For Banks With Foreign Operations, Data For
   * December 72 Through December 1975 Are Domestic Only
   * @property {number} [data.eSUBND] Interest Expense On Subordinated Notes
   * And Debentures On A Consolidated Basis
   * Note:
   * 1. This Item Is Not Reported By Form 51 Filers
   * 2. For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.eXTRA] Discontinued Operations, Net Of Applicable
   * Income Taxes On A Consolidated Basis
   *
   * Note:
   * (1) Prior To March 2016, Defined As Extraordinary Items And And Other
   * Adjustments, Net Of Taxes On A Consolidated Basis
   * (2) This Item Does Not Include The Tax Effects Related To Securities Gains
   * And Losses And Extraordinary Items From June 1984 Through December 1985
   * For Bif Thrifts (Refer To Applicable Income Taxes)
   * (3) For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.fdBIF] FDIC Supervised, BIF Insured Institutions
   * @property {number} [data.fdSAIF] FDIC supervised SAIF insured institutions
   * @property {number} [data.fREPO] Federal Funds Sold And Securities
   * Purchased Under Agreements To Resell On A Consolidated Basis
   *
   * Note:
   * (1) Prior To March 1997, Includes Only Federal Funds Sold And Securities
   * Purchased Under Agreements To Resell In Domestic Offices Of The Bank And
   * Of Its Edge And Agreement Subsidiaries, And In Ibf'S
   * (2) Prior To March 1998, Includes Only Federal Funds Sold For Tfr Filers
   * (3) For Banks With Foreign Operations, Data For March & September Of 1972
   * Through 1975 Was Reported On A Domestic Basis
   * @property {number} [data.fREPP] Federal Funds Purchased And Securities
   * Sold Under Agreements To Repurchase On A Consolidated Basis
   * Note:
   * (1) Prior To March 1998, Includes Only Reverse Repurchase Agreements For
   * Tfr Filers
   * (2) For Banks With Foreign Operations Data For March & September Of 1972
   * Through 1975 Are Reported On A Domestic Basis
   * @property {number} [data.iCHBAL] Total Interest Income On Balances Due
   * From Depository Institutions On A Consolidated Basis
   * @property {number} [data.iFEE] Fee Income (Represents service charges on
   * deposit accounts such as maintenance fees, activity charges,
   * administrative charges, overdraft charges and check certification charges;
   * mortgage loans servicing fees plus other fees and charges, including
   * prepayment loan fees, late charges, assumption fees, and amortization of
   * commitment fees.)
   * @property {number} [data.iFREPO] Interest Income On Federal Funds Sold And
   * Securities Purchased Under Agreements To Resell On A Consolidated Basis
   * Note:
   * (1) Prior To March 1997 Included Only Income From Domestic Offices Of The
   * Bank And Of Its Edge And Agreement Subsidiaries, And In Ibfs On A
   * Consolidated Basis
   * (2) For Banks With Foreign Operations Data For December 1972 Through 1975
   * Are Domestic Only
   * @property {number} [data.iGLSEC] Realized Gains (Losses) On
   * Held-To-Maturity And Available-For-Sale Debt Securities And Unrealized
   * Holding Gains (Losses) On Equity Securities Not Held For Trading Before
   * Adjustments For Income Taxes On A Consolidated Basis (Also Includes
   * Realized Gains On Equity Securities Until The Institution Adopts Asu
   * 2016-01)
   * Note:
   * 1. Prior To March 2018, Defined As Realized Gains (Losses) On
   * Held-To-Maturity And Available-For-Sale Securities Before Adjustments For
   * Income Taxes On A Consolidated Basis
   * 2. Beginning In The 2018 Reporting Year, Includes Unrealized Gains
   * (Losses) On Equity Securities For Institutions That Adopted Asu2016-01 And
   * Includes Realized Gains (Losses) On Equity Securities For Institutions
   * That Have Not Yet Adopted Asu2016-01
   * 3. Prior To March 1994 Defined As Gains (Losses) On Securities Not Held In
   * Trading Accounts
   * 4. From March 1990 Through March 2009, Includes Gains (Losses) On Assets
   * Held For Sale For Tfr Filers
   * 5. Includes Gains (Losses) On Loans Held For Investment From March 1984
   * Through December 1989 For Tfr Filers
   * 6. Tfr Filers Report Only Gains From March 1984 Through December 1986
   * 7. For Banks With Foreign Operations Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.iLNDOM] Total Interest And Fees On Loans Held In
   * Domestic Offices
   * Note:
   * (1) U-Size-Stratum = 0001 Means That Bank Has Total Assets Less Than $25
   * Million
   * (2) U-Size-Stratum = 0002 Means That Bank Has Total Assets Equal To Or
   * Greater Than $25 Million
   * (3) For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.iLNFOR] Total Interest And Fees On Loans Held In
   * Foreign Offices, Edge And Agreement Subsidiaries, And Ibf'S
   * @property {number} [data.iLNLS] Interest And Fees On Loans And Lease
   * Financing Receivables On A Consolidated Basis
   * Note:
   * (1) U-Size-Stratum = 0001 Means That Bank Has Total Assets Less Than $25
   * Million
   * (2) U-Size-Stratum = 0002 Means That Bank Has Total Assets Equal To Or
   * Greater Than $25 Million
   * (3) For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.iLNS] Loans (Represents all interest, fees and
   * similar charges levied against or associated with all assets reportable as
   * loans. Includes interest, yield related fees, commitment fees, service
   * charges on loans and discount accretion. (One savings bank with an office
   * in Canada has been reporting on the Domestic & Foregin Consolidated Call
   * Report form (FFIEC 031). It does not, however, indicate any income or
   * expenses related to foregin operations.))
   * @property {number} [data.iLS] Total Interest Income From Lease Financing
   * Receivables On A
   * Consolidated Basis
   * @property {number} [data.iNTAN] Intangible Assets On A Consolidated Basis
   * @property {number} [data.iNTBAST] Total Interest Earning Assets (Derived
   * See Si-19) - Sc
   * @property {number} [data.iNTBLIB] Total Interest Bearing Liabilities
   * (Derived See Si-19) - Sc
   * @property {number} [data.iNTINC] Total Interest Income On A Consolidated
   * Basis
   * Note: For Banks With Foreign Operations Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.iNTINC2] INTINC2
   * @property {number} [data.iRAKEOGH] Individual Retirement Accounts (Ira'S)
   * And Keogh Plan
   * Accounts Held In Domestic Offices
   * Note: Listed As Memoranda Only
   * @property {number} [data.iSC] Total Interest And Dividend Income On: U.S.
   * Treasury Securities, U.S. Government Agency And Corporation Obligations,
   * Securities Issued By States And Political
   * Subdivision In The U.S., Other Domestic Debt Securities, Foreign Debt
   * Securities, And Equity Securities (Including Investments In Mutual Funds)
   * On A Consolidated Basis
   * Note:
   * (1) This Item Includes Interest Income On Deposits For Tfr Filers
   * (2) Includes Interest Income On Assets Held In Trading Accounts For Tfr
   * Filers For Two Distinct Periods: (A) March 1984 Through December 1989 And
   * (B) June 1996
   * And Following Quarters.
   * (3) For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.iSERCHG] Represents service charges on deposit
   * accounts in domestic offices such as maintenance fees, activity charges,
   * administrative charges, overdraft charges, and check certification charges
   * @property {number} [data.iTAX] Represents Federal, state and local taxes
   * on income. It does not include taxes relating to securities transactions
   * or extraordinary items
   * @property {number} [data.iTAXR] Pre-Tax Net Operating Income (Represents
   * Net Interest Income plus Total Noninterest Income less Total Noninterest
   * Expense and the Provision for Loan & Lease Losses.)
   * @property {number} [data.iTRADE] Interest Income From Assets Held In
   * Trading Accounts On A Consolidated Basis
   * Note:
   * Beginning March 2017, Reported As An Individual Income Category For Form
   * 031 Filers Only And Is Included As A Component Of Other Interest Income
   * For All Other Report Forms
   * @property {number} [data.lIAB] Total Liabilities Including Subordinated
   * Notes And Debentures And Limited Life Preferred Stock And Related Surplus
   * On A Consolidated Basis
   * Note: Prior To March 2009, This Item Included Noncontrolling (Minority)
   * Interests In Consolidated Subsidiaries For Call Report And Tfr Filers
   * @property {number} [data.lIABEQ] Total Liabilities, Limited-Life Preferred
   * Stock, And Equity Capital On A Consolidated Basis Note: For Banks With
   * Foreign Operations Data For March & September Of 1972 Through 1975 Are
   * Reported On A Domestic Basis
   * @property {number} [data.liqasstd] Represents all assisted payouts of
   * FDIC-insured savings institutions that are not in RTC conservatorship.
   * @property {number} [data.liqunass] Represents all instances where the
   * owners of a thrift voluntarily surrender their charter with all
   * liabilities including deposits paid down and all assets sold.
   * @property {number} [data.lNAG] Loans To Finance Agricultural Production
   * And Other Loans To Farmers On A Consolidated Basis
   * Note: For Banks With Foreign Operations, Data For All Periods Form
   * December 1972 Through September 1978 Are Domestic Only
   * @property {number} [data.lNALLOTH] All Other Loans (1969-Present --
   * Represents Federal funds purchased, securities sold under agreements to
   * repurchase, demand notes issued to the US Treasury, mortgage indebtedness,
   * liabilities under capitalized leases and all other liabilities for
   * borrowed money. -- 1934-1968 -- Does not include mortgage indebtedness
   * which is netted against bank premises.)
   * @property {number} [data.lNATRES] Allowance For Loan And Lease Financing
   * Receivable Losses And Allocated Transfer Risk On A Consolidated Basis
   * Note:
   * (1) From March 2001 To Dec 2002 Allocated Transfer Riskis Netted From
   * Loans & Not Included As Part Of The Reserve
   * (2) Additional Detail Can Be Found On Schedule Ri-B
   * (3) For Tfr Filers Between March 1984 Through December 1989 Includes
   * Allowance For Mortgage Pool Securities
   * (4) For Banks With Foreign Operations, Data For March & September Of 1972
   * Through 1975 Was Reported On A Domestic Basis
   * @property {number} [data.lNAUTO] Represents installment loans to purchase
   * private passenger automobiles, both direct loans and purchased paper
   * @property {number} [data.lNCI] Commercial And Industrial Loans On A
   * Consolidated Basis Note: For Banks With Foreign Operations, Data For All
   * Periods From December 1972 Through September 1978 Are Domestic Only
   * @property {number} [data.lNCON] Loans To Individuals For Household,
   * Family, And Other Personal Expenditures (Consumer Loans) On A Consolidated
   * Basis
   * Note:
   * (1) For Tfr Filers Includes Revolving Loans Secured By 1-4 Family Dwelling
   * Units From March 1984 Through March 1988
   * (1) For Banks With Foreign Operations, Data For All Periods From December
   * 1972 Through September 1978 Are Domestic Only
   * @property {number} [data.lNCONOT1] Installment Loans To Individuals To
   * Repair And Modernize
   * Residential Property Held In Domestic Offices
   * @property {number} [data.lNCONOTH] Represents all other loans to
   * individuals for household, family and other personal expenditures. It
   * includes auto loans, both direct and indirect, mobile homes (unless
   * secured by a real estate mortgage), education loans, other installment
   * loans both secured by personal property or unsecured, and single payment
   * loans (time or demand, secured or unsecured)
   * @property {number} [data.lNCRCD] Credit Cards Related Plans On A
   * Consolidated Basis
   *
   * Note:
   * (1)Prior To March 2001 Includes Credit Cards Related Plans-Loans To
   * Individuals For Household, Family, And Other Personal Expenditures
   * (Consumer Loans) Includes Check Credit And Other Revolving Credit Plans
   * (2) For Tfr Filers Between March 1984 Through March 1988 This Figure
   * Includes Home Equity Loans Based On The Creditworthiness Of The Borrower
   * (T-Sc340)
   * (3) For Banks With Foreign Operations, Data For All Periods From December
   * 1972 Through September 1978 Are Domestic Only
   * @property {number} [data.lNDEP] Loans To Depository Institutions On A
   * Consolidated Basis
   * Note: For Banks With Foreign Operations, Data For All Periods From
   * December 1972 Through September 1978 Are Domestic Only
   * Note:(1) Beginning March 2001 Includes Acceptances Of Other Banks
   * (2) Beginning March 2001, Includes Acceptances Of Other Banks For Ibas
   * @property {number} [data.lNLS] Represents the sum of all components of
   * loans
   * @property {number} [data.lNLSGR] Loans And Lease Financing Receivables,
   * Net Of Unearned Income, On A Consolidated Basis
   * Note:
   * (1) Additional Detail Can Be Found On Schedule Rc-C
   * (2) For Tfr Filers This Item Is Net Of Unamortized Yield Adjustments For
   * Mortgage Pool Securities From March 1984 Through December 1989
   * (3) For Banks With Foreign Operations, Data For March & September Of 1972
   * Through 1975 Was Reported On A Domestic Basis
   * @property {number} [data.lNLSNET] Loans And Lease Financing Receivables,
   * Net Of Unearned Income, Allowance, And Reserve On A Consolidated Basis
   * Note:
   * (1) For Tfr Filers This Item Is Net Of Valuation Allowances And
   * Unamortized Yield Adjustments For Mortgage Pool Securities From March 1984
   * Through
   * (2) For Banks With Foreign Operations, Data For March & September Of 1972
   * Through 1975 Are Reported On A Domestic Basis
   * @property {number} [data.lNMOBILE] Represents loans to individuals to
   * purchase mobile homes. (If the bank's security interest in the loan was
   * represented by a mortgage or deed of trust, the loan should be included in
   * real estate loans)
   * @property {number} [data.lNMUNI] Obligations (Other Than Securities And
   * Leases) Of States And Political Subdivisions In The U.S. (Including
   * Nonrated Industrial Development Obligations) On A Consolidated Basis
   * @property {number} [data.lNRE] Loans Secured By Real Estate On A
   * Consolidated Basis
   * Note:
   * (1) For Tfr Filers Between March 1984 Through March 1988 This Figure
   * Excludes Home Equity Loans Based On The Creditworthiness Of The Borrower
   * (T-Sc340)
   * (2) For Banks With Foreign Operations, Data For All Periods From December
   * 1972 Through September 1978 Are Domestic Only
   * @property {number} [data.lNREAG] Represents loans secured by farmland,
   * including improvements, and other land known to be used or usable for
   * agricultural purposes, as evidenced by mortgages or other liens. It
   * includes loans secured by farmland that are guaranteed by the Farmers Home
   * Administration (FHA) or by the Small Business Administration
   * @property {number} [data.lNRECONS] Construction And Land Development Loans
   * Secured By Real Estate Held In Domestic Offices
   * Note: For Tfr Filers Portions Of Lnrecons Were Included In Other Real
   * Estate Loan Categories Prior To March 30, 1986
   * @property {number} [data.lNREDOM] Represents the total of all loans
   * secured by real estate in domestic offices (U.S. and other areas)
   * @property {number} [data.lNREFOR] Represents all loans secured by real
   * estate in foreign offices
   * @property {number} [data.lNRELOC] Revolving, Open-End Loans Secured By 1-4
   * Family Residential Properties And Extended Under Lines Of Credit Held In
   * Domestic Offices
   * @property {number} [data.lNREMULT] Multifamily (5 Or More) Residential
   * Properties Secured By Real Estate Held In Domestic Offices
   * @property {number} [data.lNRENRES] Nonfarm Nonresidential Properties
   * Secured By Real Estate Held In Domestic Offices
   * Note: For Tfr Filers This Figure Includes Mortgages On Properties That Are
   * Used For Farming
   * @property {number} [data.lNRERES] Total Loans Secured By 1-4 Family
   * Residential Properties Held In Domestic Offices
   * Note: For Tfr Filers Between March 1984 Through March 1988 This Figure
   * Excludes Home Equity Loans Based On The Creditworthiness Of The Borrower
   * @property {number} [data.lNRESRE] Allowance For Loan Losses On Real Estate
   * Loans On A Consolidated Basis
   * Note: For Tfr Filers Includes Allowance For Mortgage Pool Securities
   * Between March 1984 Through December 1989
   * @property {number} [data.lNSP] All loans both time or demand, secured or
   * unsecured, to individuals for personal, family or other household
   * expenditures
   * @property {number} [data.ls] Lease Financing Receivables (Net Of Unearned
   * Income) On A Consolidated Basis
   * Note: For Banks With Foreign Operations, Data For March & September Call
   * Dates Are Domestic Only Through December 1975
   * @property {number} [data.mERGERS] Mergers, consolidations or absorptions
   * entered into as a result of supervisory actions. The transaction may or
   * may not have required FDIC assistance.
   * @property {number} [data.mISSADJ] Represents any FDIC-insured savings
   * institution that did not file a financial report during the year in which
   * the charter was added or deleted.
   * @property {number} [data.mTGLS] Represents mortgage indebtedness and
   * liabilities under capitalized leases
   * @property {number} [data.nALNLS] Total Nonaccrual Loans And Lease
   * Financing Receivables On A Consolidated Basis
   * @property {number} [data.nCHGREC] Net Loans And Leases Charge Offs (--
   * 1984-1989 -- Represents Loan and Lease Charge-offs less Loan and Lease
   * Recoveries. An amount enclosed in paraentheses indicates net recoveries.
   * Not collected by TFR filers. -- 1990-Present -- Represents Loan and Lease
   * Charge-offs less Loan and Lease Recoveries. An amount enclosed in
   * paraentheses indicates net recoveries.)
   * @property {number} [data.nCLNLS] Total Loans And Lease Financing
   * Receivables 90 Days Or More Past Due And Nonaccrual On A Consolidated
   * Basis
   * Note: Includes Delinquent Loans (60 Or More Days Overdue) And Past Due
   * Loans (One Or More Payments Missed) For Tfr Filers Prior To March 1990
   * @property {number} [data.nETINC] Net Income Attributable To The Bank On A
   * Consolidated Basis
   * Note: For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.newcount] Institutions newly chartered by federal
   * or state banking authorities including authorities in the U. S.
   * Territories or possessions.
   * @property {number} [data.newChar] Institutions newly licensed or chartered
   * by the Office of the Comptroller of the Currency (national banks) or by
   * state banking authorities, including banking authorities in the U. S.
   * territories or possessions. Includes de novo institutions as well as
   * charters issued to take over a failing institution.
   * @property {number} [data.nEW61] Represents interest expense related to
   * demand notes issued to the U. S. Treasury, mortgage indebtedness,
   * obligations under capitalized leases, and other borrowed money
   * @property {number} [data.nEW91] Represents all other assets not included
   * in previously mentioned captions. Includes, for the most part, customers'
   * liabilities on acceptances outstanding, income earned not collected as
   * well as any other asset not included above
   * @property {number} [data.nEW101] Represents all securities, bonds, notes
   * and debentures of domestic and foreign corporations. Also includes
   * privately issued or guaranteed mortgage backed securities and certain
   * detached U.S. Government security coupons held as a result of either their
   * purchase or the bank's stripping them (CATS, TIGRs, COUGARs, LIONs and
   * ETRs).
   * @property {number} [data.nEW102] Securities within the scope of ASC Topic
   * 320, Investments – Debt Securities, that a bank has elected to report at
   * fair value under a fair value option with changes in fair value reported
   * in current earnings should be classified as trading securities.
   * (https://www.fdic.gov/regulations/resources/call/crinst/2018-06/031-041-618rc-d-063018.pdf)
   * @property {number} [data.nEW103] For all years except 1969-1973,
   * investment securities are reflected net of general valuation reserves.
   * Specific reserves are deducted from each security so reserved
   * @property {number} [data.nEW111] Represents unplanned overdrafts and loans
   * to: brokers and dealers in securities, any borrower for the purpose of
   * purchasing and carrying securities, nonprofit institutions and
   * organizations, individuals for investment purposes, real estate investment
   * trusts, mortgage companies holding companies of depository institutions,
   * insurance companies, finance companies, factors and other financial
   * intermediaries, federally sponsored lending agencies, investment banks,
   * the bank's own trust department, Small Business Investment Companies,
   * foreign governments and official institutions, and any other loan not
   * included in one of the above categories
   * @property {number} [data.nEW141] Represents Federal funds purchased,
   * securities sold under agreements to repurchase, demand notes issued to the
   * US Treasury, mortgage indebtedness, liabilities under capitalized leases
   * and all other liabilities for borrowed money
   * @property {number} [data.nEW142] Includes all liabilities not included
   * above and limited life preferred stock
   * @property {number} [data.nEW143] Represents the total of all components of
   * liabilities
   * @property {number} [data.nEW144] Represents undivided profits and related
   * accounts
   * @property {number} [data.nEW151] Represents all deposits of individuals,
   * partnerships and corporations in domestic and foreign offices
   * @property {number} [data.nEW152] Represents all deposits of individuals,
   * partnerships and corporations in domestic and foreign offices
   * @property {number} [data.nEW153] Represents all deposits of states,
   * counties and municipalities in domestic offices. Such deposits, if any, in
   * foreign offices are not separately reported
   * @property {number} [data.nEW154] Represents all other deposits. Includes
   * deposits of financial institutions, both domestic and foreign, deposits of
   * foreign governments and official institutions and certified and official
   * checks. Also includes deposits in foreign offices other than those of
   * individuals, partnerships and corporations
   * @property {number} [data.nEW155] Represents all savings deposits in
   * domestic offices
   * @property {number} [data.nEW157] Total Domestic Deposits
   * @property {number} [data.nEW161] Represents demand notes issued to the
   * U.S. Treasury (Treasury tax & loan account), and all other borrowings.
   * Includes mortgage indebtedness and liabilities under capitalized leases
   * for Call report filers. Includes FSLIC net worth certificates for TFR
   * filers
   * @property {number} [data.nEW162] Represents any deposit in domestic and
   * foreign offices on which the banks pays or accrues interest
   * @property {number} [data.nIM] Net Interest Income (Total Interest Income
   * Minus Total Interest Expense) On A Consolidated Basis
   * Note: For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.nONII] Total Noninterest Income On A Consolidated
   * Basis
   * Note:
   * (1) From March 1990 Through March 2009, Excludes Gains (Losses) On Assets
   * Held For Sale For Tfr Filers, See Tfr Instructions For So430
   * (2) Excludes Gains On The Sale Of Loans Held For Investments From March
   * 1984 Through December 1989 For Tfr Filers
   * (3) For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.nONIX] Total Noninterest Expense On A
   * Consolidated Basis
   * Note:
   * (1) Excludes Losses On Asset Sales For Tfr Filers Beginning June 1996
   * (2) Includes Loss On Sale Of Mortgage Pool And Other Securities Held For
   * Investment For Tfr Filers From March 1984 Through December 1986
   * (3) Excludes Losses On Loans Held For Investment For Tfr Filers From March
   * 1987 Through December 1989
   * (4) For Banks With Foreign Operations, Data For December 1972 Through
   * December 1975 Are Domestic Only
   * @property {number} [data.nTLNLS] Represents Loan and Lease Charge-offs
   * less Loan and Lease Recoveries. An amount enclosed in parentheses
   * indicates net recoveries. Not collected by TFR filers
   * @property {number} [data.nTR] Represents deposits that are not included in
   * the definition of transaction accounts above or that do not satisfy the
   * criteria necessary to be defined as a transaction account. MMDA's are
   * specifically defined as nontransaction accounts
   * @property {number} [data.nTRTIME] Represents all time certificates of
   * deposit, time open accounts and similar deposits in domestic offices
   * @property {number} [data.nTRTMLG] Time Deposits Over $100,000 Or More Held
   * In Domestic Offices
   * Note:
   * (1) Listed As Memoranda Only And Is Included In Total Nontransaction
   * Accounts
   * (2) Prior To March 2007, Includes All Deposits (Not Just Time) Greater
   * Than $100,000 For Tfr Filers. Except For December 2006, Includes All
   * Nonretirement Deposits Over
   * $100,000 And All Retirement Deposits Over $250,000 For Tfr Filers
   * (3) Includes Time Deposits Of $100,000 Or More
   * @property {number} [data.nUMEMP] Number Of Full Time-Equivalent Employees
   * On Payroll At The End Of The Current Period
   * Note:
   * (1) Listed As Memoranda Only
   * (2) For Banks With Foreign Operations Data For March & September Of 1972
   * Through 1975 Are Reported On A Domestic Basis
   * @property {number} [data.oEA] Other Earning Assests (-- 1984-1989 --
   * Represents Federal funds sold and securities purchased under agreements to
   * resell (repurchase agreements). Items not separately reported by TFR
   * filers. They are included in Secruties. -- 1990-Present -- Represents
   * Federal funds sold and securities purchased under agreements to resell
   * (repurchase agreements). Includes only Federal funds sold for TFR filers.
   * Repurchase agreements are included in Securities.)
   * @property {number} [data.oFFICES] Offices include: Multiple service
   * offices, Military facilities, Drive-in facilities, Loan production
   * offices, Consumer credit offices, Seasonal offices, Administrative
   * offices, Messenger service offices, Supermarket banking offices, and Other
   * offices.
   * @property {number} [data.oINTBOR] Demand Notes And Other Borrowings
   * (Represents demand notes issued to US Treasury (Treasury tax & loan
   * account), and all other borrowings. Includes mortgage indebtedness and
   * liabilities under capitalized leases for Call report filers. Includes
   * FSLIC net worth certificates for TFR filers.)
   * @property {number} [data.oINTEXP] Total Other Interest Expenses (Federal
   * Funds Purchased and Securities Sold -- Represents the gross expense of all
   * liabilities reportable under this category. This item is not reported
   * separately by TFR filers. It is included in Borrowed Money).
   * @property {number} [data.oINTINC] Total Other Interest Income (Represents
   * the total of all Other Interest Income components).
   * @property {number} [data.oONONII] Other Non Interest Income (1984-1989 --
   * Same as Total Other Interest Income except gains on the sale of loans held
   * for investment are excluded for TFR filers. -- 1990- Present -- Represents
   * income derived from the sale of assets held for sale; office building
   * operations; real estate held for investment; REO operations; LOCOM
   * adjustments made to assets held for sale; net income (loss) from
   * investements in service corporations/subsidiaries (other than operating or
   * finance subsidiaires); leasing operations; realized and unrealized gains
   * (losses) on trading assets; gains on the sale of REO real estate held for
   * investment, and loans held for investment; and the amoritization of
   * deferred gains (losses) on asset hedges.)
   * @property {number} [data.oRE] Other Real Estate Owned On A Consolidated
   * Basis
   * Note:
   * (1) Prior To June 2009, Includes Direct And Indirect Investments In Real
   * Estate
   * (2) For Banks With Foreign Operations Data For March & September Of 1972
   * Through 1975 Was Reported On A Domestic Basis
   * @property {number} [data.oRET] Other Real Estate (Represents other real
   * estate owned net of reserves for losses). Not available for 1997. For 1986
   * through 1988 ORET = ORE + INVSUORE; for all other years ORET = ORE
   * @property {number} [data.otBIF] Non FDIC supervised BIF insured
   * institutions
   * @property {number} [data.otSAIF] Non FDIC supervised SAIF insured
   * institutions
   * @property {number} [data.oTHASST] All Other Assets (Same as Other Real
   * Estate except that investment in service corporations/subsidiaries is
   * reported gross of valuation allowances by TFR filers, and assets held in
   * trading accounts are included in Securities for TFR filers. --
   * 1990-Present -- Represents all associations assets not previously
   * mentioned. Includes all non real estate repossessed property, investment
   * in service corporations/subsidiaries, property leased to others, income
   * earned but not yet collected, assets held in the trading accounts, and
   * miscellaneous assets) For 2009- present OTHASST = SUM (INVSUB + INVSUORE +
   * CUSLI + OA)
   * @property {number} [data.oTHBFHLB] Other Liabilities From The Fhlb
   * Note:Prior To March 2001 Only Reported On Tfrs
   * @property {number} [data.oTHBORR] Borrowed Money (Represents interest
   * expense related to demand notes issued the US Treasury, mortage
   * indebtedness, obligations under capitalized leases and on other borrowed
   * money.
   * @property {number} [data.oTHEQ] Represents all equity securities not held
   * for trading: investment in mutual funds, common stock of FNMA, Student
   * Loan Marketing Association, Federal Home Loan Mortgage Corporation,
   * Federal Reserve Bank stock, Federal Home Loan Bank stock, minority
   * interests not meeting the definition of associated companies, "restricted"
   * stock, and other equity securities in both domestic and foreign
   * corporations
   * @property {number} [data.oTHER] Withdrawals from FDIC insurance, voluntary
   * liquidations, or conversions to institutions that are not considered
   * commercial banks. Also includes relocation of banks from one state to
   * another.
   * @property {number} [data.oTHLIAB] Other Liabilities (Includes all
   * liabilities not included above and limited life preferred stock. 2001-
   * present -- Includes OTHER LIAB & MINOR IN SUBS).
   * @property {number} [data.oTHNBORR] Borrowed Funds (Includes federal funds
   * purchased, securities sold under agreements to repurchase (reverse
   * repurchase agreements), demand notes issued to the US Treasury, mortgage
   * indebtedness, liabilities under capitalized leases and all other
   * liabilities for borrowed money. Includes only reverse purchase agreements
   * (securities sold under agreements to repurchase) and FSLIC net worth
   * certificates for TFR filers)
   * @property {number} [data.oTLNCNTA] Other Contracts (Represents amount
   * reported by savings institutions that file on the Thrift Financial Report.
   * Contra accounts include accrued interest receivable, unamortized yield
   * adjustments and valuation allowances. Negative amounts reflect unamortized
   * premiums and deferred direct costs exceeding unamortized discounts and
   * deferred loan fees).
   * @property {number} [data.pAIDOFF] Institutions that were declared
   * insolvent, the insured deposits of which were paid by the FDIC.
   * @property {number} [data.p3LNLS] Total Loans And Lease Financing
   * Receivables Past Due 30 Through 89 Days And Still Accruing Interest On A
   * Consolidated Basis
   * Note:
   * (1) Prior To March 2001,This Information On An Institution Level Is
   * Considered Confidential By The Ffiec
   * @property {number} [data.p9LNLS] Total Loans And Lease Financing
   * Receivables Past Due 90 Or More Days And Still Accruing Interest On A
   * Consolidated Basis
   * @property {number} [data.pTXNOINC] Pre-Tax Net Operating Income
   * @property {number} [data.rELCO] Conversions of existing institutions of
   * any type that meet the definition of commercial banks (see Definition of
   * Total Commercial Banks and have applied for and received FDIC insurance.
   * Also includes bank relocations from one state to another.
   * @property {number} [data.sAVINGS] Total Insured Savings Institutions
   * including institutions that did not file a 12/31 fincncial report and
   * other adjustments (See Notes to User).
   * @property {number} [data.sc] Total Securities: The Sum Of Held-To-Maturity
   * Securities At Amortized Cost, Available-For-Sale Securities At Fair Value
   * And Equity Securities With Readily Determinable Fair Values Not Held For
   * Trading On A Consolidated Basis
   * Note:
   * 1. Prior To March 2018, Defined As Total Held-To-Maturity At Amortized
   * Cost And Available-For-Sale At Fair Value Securities (Excludes Assets Held
   * In Trading Accounts) On A Consolidated Basis
   * 2. Beginning In 2018, Includes Equity Securities For Institutions That
   * Have Adopted Asu2016-01 And Those Institutions That Have Not Yet Adopted
   * This Accounting
   * Standard
   * 3. Prior To March 1994 Item Defined As Book Value
   * 4. Additional Detail Can Be Found On Schedule Rc-B
   * 5. For Tfr Filers Between March 1984 Through December 1989 Includes
   * Interest-Earning Deposits In Fhlbs, Other Interest-Earning Deposits,
   * Federal Funds Sold And Assets Held In Trading Accounts
   * 6. For Banks With Foreign Operations Data For March & September Of 1972
   * Through 1975 Are Reported On A Domestic Basis
   * @property {number} [data.sCAGE] Total U.S. Government Agency And
   * Corporation Obligations On A Consolidated Basis
   * Note:
   * 1) From June 2009 Through December 2010, This Item Excluded Other
   * Commercial
   * Mortgage-Backed Securities
   * 2) Prior To June 2009, This Item Included Other Commercial Mortgage-Backed
   * Securities
   * 3) Beginning March 1994 Consists Of Held-To-Maturity At Amortized Cost And
   * Available-For-Sale At Fair Value Securities
   * 4) Includes The Aforementioned Securities Held In Trading Accounts For Tfr
   * Filers
   * 5) Includes U.S. Treasury Securities For Tfr Filers Between March 1984
   * Through December 1989 And After March 1996
   * 6) Does Not Include Mortgage Derivative Securities For Tfr Filers Between
   * March 1984 Through December 1986
   * 7) For Banks With Foreign Operations, Data For March & September Of 1973
   * Through 1975 Are Reported On A Domestic Basis
   * @property {number} [data.sCEQ] Total Equity Securities Available-For-Sale
   * At Fair Value On A Consolidated Basis
   * Note:
   * (1) Beginning March 2018 Does Not Include Equity Securities For
   * Institutions That Have Adopted Asu 2016-01 See Sceqfv
   * (2) Includes The Aforementioned Securities Held In Trading Accounts For
   * Tfr Filers
   * @property {number} [data.sCMTGBK] Mortgage Backed Securities On A
   * Consolidated Basis
   * Includes:
   * (1) U.S. Government Agency And Corporation Obligations Issued Or
   * Guaranteed Certificates Of Participation In Pools Of Residential
   * Mortgages,
   * (2) U.S. Government Agency And Corporation Obligations Collateralized
   * Mortgage Obligations Issued By Fnma And Fhlmc (Including Remics)
   * (3) Other Domestic Debt Securities - Private (I.E.,
   * Non-Government-Issued-Or-Guaranteed) Certificates Of Participations In
   * Pools Of Residential Mortgages, And
   * (4) Other Domestic Debt Securities - Privately-Issued Collateralized
   * Mortgage Obligations (Including Remics)
   * @property {number} [data.sCMUNI] Total Securities Issued By States And
   * Political Subdivisions Held-To-Maturity At Amortized Cost And
   * Available-For-Sale At Fair Value On A Consolidated Basis
   * Note:
   * (1) Prior To March 1994 Item Was Defined As Book Value
   * (2) Includes The Aforementioned Securities Held In Trading Accounts For
   * Tfr Filers
   * (3) For Banks With Foreign Opeations, Data For March & September Of 1973
   * Through 1975 Are Reported On A Domestic Basis
   * @property {number} [data.sCMV] Represents the market (fair) value of all
   * investment securities
   * @property {number} [data.sCRES] Contra-Assets To Securities (Reserves)
   * Note: For Tfr Filers Only
   * @property {number} [data.sCUS] Total U.S. Treasury Securities And U.S.
   * Government Agency And Corporation Obligations On A Consolidated Basis
   * Note:
   * 1) From June 2009 Through December 2010 This Item Excluded Commercial
   * Mortgage Backed Securities
   * 2) Prior To June 2009, This Item Included Commercial Mortgage Backed
   * Securities
   * 3) Beginning March 1994 Consists Of Held-To-Maturity At Amortized Cost And
   * Available-For-Sale At Fair Value Securities
   * 4) Does Not Include Mortgage Derivative Securities From March 1984 Through
   * December 1986 For Tfr Filers
   * 5) Includes The Aforementioned Securities Held In Trading Accounts For Tfr
   * Filers
   * 6) For Banks With Foreign Operations Data For March & September Of 1973
   * Through 1975 Are Reported On A Domestic Basis
   * @property {number} [data.sCUSA] Securities Of Us Agencies
   * @property {number} [data.sCUST] U.S. Treasury Securities Held-To-Maturity
   * At Amortized Cost And Available-For-Sale At Fair Value On A Consolidated
   * Basis
   * Note:
   * (1) Beginning June 1996, Tfr Filers No Longer Report U.S. Treasury
   * Securities Separately
   * (2) Prior To March 1994 Item Was Defined As Book Value
   * (3) Includes The Aforementioned Securities Held In Trading Accounts For
   * Tfr Filers
   * (4) For Banks With Foreign Operations, Data For March & September Of 1973
   * Through 1975 Are Reported On A Domestic Basis
   * @property {string} [data.sTNAME] State Name
   * @property {string} [data.sTNUM] State Number
   * @property {number} [data.sUBLLPF] Subordinated Notes And Debentures And
   * Limited-Life Preferred Stock And Related Surplus On A Consolidated Basis
   * Note: (1) Banks With Foreign Operations Data For March & September Of 1972
   * Through 1975 Are Reported On A Domesitc Basis
   * @property {number} [data.sUBND] Represents all notes and debentures
   * subordinated to deposits and all capital notes and debentures
   * @property {number} [data.tINTINC] Total Other Interest Income (Represents
   * the sum of Other Interest Income - Investment Securities, Trading Account
   * Assets, Federal Funds Sold and Securities Purchased, and Balanaces Due
   * from Depository Institutions)
   * @property {number} [data.tochrt] Represents the charter transfer of
   * existing FDIC-insured savings institutions to an FDIC-insured commercial
   * bank charter.
   * @property {number} [data.tofail] Represents the absorption of a failing
   * savings institution by a commercial bank with assistance from either the
   * BIF or SAIF.
   * @property {number} [data.tOINTEXP] Total Other Interest Expense
   * (Represents the sum of all components of Other Interest Expense)
   * @property {number} [data.tomerg] Represents the absorption of a savings
   * institution charter by a commercial bank without assistance.
   * @property {number} [data.tortc] Represents institutions that were declared
   * failed and placed under RTC conservatorship until a buyer(s) is(are) found
   * or a payout to depositors occurs.
   * @property {number} [data.tOTAL] Total Insured Commercial Banks including
   * institutions that did not file a 12/31 fincncial report and other
   * adjustments (See Notes to User)
   * @property {number} [data.tOTFDIC] Total FDIC Supervised Savings
   * Institutions
   * @property {number} [data.tOTOTS] Total Non FDIC Supervised Savings
   * Institutions
   * @property {number} [data.tOTSAVE] All FDIC Insured Savings Institutions
   * filing a 12/31 financial report
   * @property {number} [data.tPD] Total Loans And Leases Past Due
   * @property {number} [data.tRADE] Assets Held In Trading Accounts On A
   * Consolidated Basis
   * Note:
   * (1) Effective March 1994 Item Reported On A Gross Basis
   * (2) Additional Detail Can Be Found On Schedule Rc-D
   * (3) For Banks With Foreign Operations Data For March & September Of 1972
   * Through 1975 Are Reported On A Domestic Basis,
   * (4) For Periods 1972 Through 1983 Includes Only Securities
   * @property {number} [data.tRADES] Trading Accounts
   * @property {number} [data.tRN] Represents all demand deposits, NOW
   * accounts, ATS accounts, accounts from which payments may be made to third
   * parties by means of an automated teller machine, a remote service unit, or
   * another electronic device, and accounts that permit third party payments
   * through use of checks, drafts, negotiable instruments, or other similar
   * instrument. (MMDA's are specifically excluded from the latter two
   * definitions)
   * @property {number} [data.uNASSIST] Voluntary mergers, consolidations or
   * absorptions of two or more institutions.
   * @property {number} [data.uNINC] Unearned Income On Loans On A Consolidated
   * Basis
   * Note: For Banks With Foreign Operations, Data For March 1976 Through
   * September 1978 Are Domestic Only
   * @property {number} [data.uNIT] Unit banks are institutions that are
   * operating only one office at which deposits are received or other banking
   * business is conducted.
   * @property {string} [data.yEAR] Statistics reported as of end of year.
   */
  constructor() {
  }

  /**
   * Defines the metadata of Summary
   *
   * @returns {object} metadata of Summary
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'summary',
      type: {
        name: 'Composite',
        className: 'Summary',
        modelProperties: {
          data: {
            required: false,
            serializedName: 'data',
            type: {
              name: 'Composite',
              className: 'SummaryData'
            }
          }
        }
      }
    };
  }
}

module.exports = Summary;
