/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Total and subtotal data (additional properties based on fields selected)
 *
 */
class Totals {
  /**
   * Create a Totals.
   * @property {number} [count] Total result count
   */
  constructor() {
  }

  /**
   * Defines the metadata of Totals
   *
   * @returns {object} metadata of Totals
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'totals',
      type: {
        name: 'Composite',
        className: 'Totals',
        modelProperties: {
          count: {
            required: false,
            serializedName: 'count',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = Totals;
