/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as moment from "moment";

export interface MetadataIndex {
  /**
   * name of index used to retrieve data
  */
  name?: string;
  /**
   * date/time index was created
  */
  createTimestamp?: Date;
}

export interface Metadata {
  /**
   * Total query result count
  */
  total?: number;
  /**
   * Query parameters supplied
  */
  parameters?: any;
  index?: MetadataIndex;
}

export interface Pathsen61rzinstitutionsgetresponses200contentapplicationJsonschema {
  meta?: Metadata;
  data?: any[];
}

export interface Pathsl90g6vlocationsgetresponses200contentapplicationJsonschema {
  meta?: Metadata;
  data?: any[];
}

export interface Paths7h3qd6summarygetresponses200contentapplicationJsonschema {
  meta?: Metadata;
  data?: any[];
}

/**
 * Total and subtotal data (additional properties based on fields selected)
*/
export interface Totals {
  /**
   * Total result count
  */
  count?: number;
}

export interface Paths1lzmfz0failuresgetresponses200contentapplicationJsonschema {
  meta?: Metadata;
  data?: any[];
  totals?: Totals;
}
