/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a MetadataIndex.
 */
class MetadataIndex {
  /**
   * Create a MetadataIndex.
   * @property {string} [name] name of index used to retrieve data
   * @property {date} [createTimestamp] date/time index was created
   */
  constructor() {
  }

  /**
   * Defines the metadata of MetadataIndex
   *
   * @returns {object} metadata of MetadataIndex
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'metadata-index',
      type: {
        name: 'Composite',
        className: 'MetadataIndex',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          createTimestamp: {
            required: false,
            serializedName: 'createTimestamp',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = MetadataIndex;
