/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Pathsen61rzinstitutionsgetresponses200contentapplicationJsonschema.
 */
class Pathsen61rzinstitutionsgetresponses200contentapplicationJsonschema {
  /**
   * Create a Pathsen61rzinstitutionsgetresponses200contentapplicationJsonschema.
   * @property {object} [meta]
   * @property {number} [meta.total] Total query result count
   * @property {object} [meta.parameters] Query parameters supplied
   * @property {object} [meta.index]
   * @property {string} [meta.index.name] name of index used to retrieve data
   * @property {date} [meta.index.createTimestamp] date/time index was created
   * @property {array} [data]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Pathsen61rzinstitutionsgetresponses200contentapplicationJsonschema
   *
   * @returns {object} metadata of Pathsen61rzinstitutionsgetresponses200contentapplicationJsonschema
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'paths·en61rz·institutions·get·responses·200·content·application-json·schema',
      type: {
        name: 'Composite',
        className: 'Pathsen61rzinstitutionsgetresponses200contentapplicationJsonschema',
        modelProperties: {
          meta: {
            required: false,
            serializedName: 'meta',
            type: {
              name: 'Composite',
              className: 'Metadata'
            }
          },
          data: {
            required: false,
            serializedName: 'data',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ObjectElementType',
                  type: {
                    name: 'Object'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = Pathsen61rzinstitutionsgetresponses200contentapplicationJsonschema;
