/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

exports.MetadataIndex = require('./metadataIndex');
exports.Metadata = require('./metadata');
exports.InstitutionData = require('./institutionData');
exports.Institution = require('./institution');
exports.Pathsen61rzinstitutionsgetresponses200contentapplicationJsonschema = require('./pathsen61rzinstitutionsgetresponses200contentapplicationJsonschema');
exports.LocationData = require('./locationData');
exports.Location = require('./location');
exports.Pathsl90g6vlocationsgetresponses200contentapplicationJsonschema = require('./pathsl90g6vlocationsgetresponses200contentapplicationJsonschema');
exports.SummaryData = require('./summaryData');
exports.Summary = require('./summary');
exports.Paths7h3qd6summarygetresponses200contentapplicationJsonschema = require('./paths7h3qd6summarygetresponses200contentapplicationJsonschema');
exports.FailureData = require('./failureData');
exports.Failure = require('./failure');
exports.Totals = require('./totals');
exports.Paths1lzmfz0failuresgetresponses200contentapplicationJsonschema = require('./paths1lzmfz0failuresgetresponses200contentapplicationJsonschema');
